automotive-dlt: /home/pfefferz/dlt-daemon/src/core_dump_handler/cityhash_c/city_c.h File Reference
city_c.h File Reference
#include <stddef.h>
#include <stdint.h>
Data Structures
struct uint128
Macros
#define Uint128Low64(x) ((x).first)
#define Uint128High64(x) ((x).second)
Typedefs
typedef uint8_t uint8
typedef uint32_t uint32
typedef uint64_t uint64
Functions
uint64 CityHash64 (const char *buf, size_t len)
uint64 CityHash64WithSeed (const char *buf, size_t len, uint64 seed)
uint64 CityHash64WithSeeds (const char *buf, size_t len, uint64 seed0, uint64 seed1)
uint128 CityHash128 (const char *s, size_t len)
uint128 CityHash128WithSeed (const char *s, size_t len, uint128 seed)
Macro Definition Documentation
#define Uint128High64 (x) ((x).second)
Definition at line 70 of file city_c.h.
Referenced by CityHash128(), CityHash128WithSeed(), CityMurmur(), and Test().
#define Uint128Low64 (x) ((x).first)
Definition at line 69 of file city_c.h.
Referenced by CityHash128(), CityHash128WithSeed(), CityMurmur(), and Test().
Typedef Documentation
typedef uint32_t uint32
Definition at line 54 of file city_c.h.
typedef uint64_t uint64
Definition at line 55 of file city_c.h.
typedef uint8_t uint8
Definition at line 53 of file city_c.h.
Function Documentation
uint128 CityHash128 (const char * s, size_t len)
Definition at line 375 of file city_c.c.
References CityHash128(), CityHash128WithSeed(), CityHashCrc128(), CityHashCrc128WithSeed(), CityHashCrc256(), Fetch64(), HashLen16(), k0, k1, k3, LIKELY, NULL, Rotate(), ShiftMix(), UInt128(), Uint128High64, and Uint128Low64.
Referenced by CityHash128(), and Test().
uint128 CityHash128WithSeed (const char * s, size_t len, uint128 seed)
Definition at line 313 of file city_c.c.
References CityMurmur(), Fetch64(), uint128::first, HashLen16(), k0, k1, LIKELY, Rotate(), uint128::second, UInt128(), Uint128High64, Uint128Low64, UNSAFE_SWAP, and WeakHashLen32WithSeeds3().
Referenced by CityHash128(), and Test().
uint64 CityHash64 (const char * buf, size_t len)
Definition at line 233 of file city_c.c.
References Fetch64(), uint128::first, HashLen0to16(), HashLen16(), HashLen17to32(), HashLen33to64(), k1, Rotate(), uint128::second, ShiftMix(), UNSAFE_SWAP, and WeakHashLen32WithSeeds3().
Referenced by CityHash64WithSeeds(), get_crashed_registers(), and Test().
uint64 CityHash64WithSeed (const char * buf, size_t len, uint64 seed)
Definition at line 273 of file city_c.c.
References CityHash64WithSeeds(), and k2.
Referenced by Test().
uint64 CityHash64WithSeeds (const char * buf, size_t len, uint64 seed0, uint64 seed1)
Definition at line 277 of file city_c.c.
References CityHash64(), and HashLen16().
Referenced by CityHash64WithSeed(), and Test().