automotive-dlt: /home/pfefferz/dlt-daemon/src/core_dump_handler/cityhash_c/city-test.cc File Reference
city-test.cc File Reference
#include <cstdio>
#include <iostream>
#include <string.h>
#include "city_c.h"
Macros
#define C(y) 0x ## y ## ULL
Functions
void setup ()
void Check (uint64 expected, uint64 actual)
void Test (const uint64 *expected, int offset, int len)
int main (int argc, char **argv)
Variables
static const uint64 k0 = 0xc3a5c85c97cb3127ULL
static const uint64 kSeed0 = 1234567
static const uint64 kSeed1 = k0
static const uint128 kSeed128 = {kSeed0, kSeed1}
static const int kDataSize = 1 << 20
static const int kTestSize = 300
static char data [kDataSize]
static int errors = 0
static const uint64 testdata [kTestSize][15]
Macro Definition Documentation
#define C (y) 0x ## y ## ULL
Definition at line 58 of file city-test.cc.
Function Documentation
void Check (uint64 expected, uint64 actual)
Definition at line 962 of file city-test.cc.
References errors.
Referenced by Test().
int main (int argc, char ** argv)
Definition at line 1023 of file city-test.cc.
References errors, kDataSize, kTestSize, setup(), Test(), and testdata.
void setup ()
Definition at line 45 of file city-test.cc.
References data, k0, and kDataSize.
Referenced by main().
void Test (const uint64 * expected, int offset, int len)
Definition at line 969 of file city-test.cc.
References Check(), CityHash128(), CityHash128WithSeed(), CityHash64(), CityHash64WithSeed(), CityHash64WithSeeds(), CityHashCrc128(), CityHashCrc128WithSeed(), CityHashCrc256(), data, kSeed0, kSeed1, Uint128High64, and Uint128Low64.
Referenced by main().
Variable Documentation
char data[kDataSize] static
Definition at line 40 of file city-test.cc.
Referenced by dlt_client_main_loop(), dlt_control_init_connection(), dlt_control_listen_to_daemon(), dlt_daemon_send_ringbuffer_to_client(), dlt_kpi_log_list(), dlt_logstorage_ctrl_execute_event_loop(), dlt_receive_message_callback(), dlt_user_trace_network_segmented_thread(), setup(), and Test().
int errors = 0 static
Definition at line 42 of file city-test.cc.
Referenced by Check(), and main().
const uint64 k0 = 0xc3a5c85c97cb3127ULL static
Definition at line 33 of file city-test.cc.
Referenced by setup().
const int kDataSize = 1 << 20 static
Definition at line 37 of file city-test.cc.
Referenced by main(), and setup().
const uint64 kSeed0 = 1234567 static
Definition at line 34 of file city-test.cc.
Referenced by Test().
const uint64 kSeed1 = k0 static
Definition at line 35 of file city-test.cc.
Referenced by Test().
const uint128 kSeed128 = {kSeed0, kSeed1} static
Definition at line 36 of file city-test.cc.
const int kTestSize = 300 static
Definition at line 38 of file city-test.cc.
Referenced by main().
const uint64 testdata[kTestSize][15] static
Definition at line 59 of file city-test.cc.
Referenced by main().