automotive-dlt: /home/pfefferz/dlt-daemon/src/core_dump_handler/cityhash_c/citycrc_c.h File Reference
citycrc_c.h File Reference
#include "city_c.h"
Functions
uint128 CityHashCrc128 (const char *s, size_t len)
uint128 CityHashCrc128WithSeed (const char *s, size_t len, uint128 seed)
void CityHashCrc256 (const char *s, size_t len, uint64 *result)
Function Documentation
uint128 CityHashCrc128 (const char * s, size_t len)
Referenced by CityHash128(), and Test().
uint128 CityHashCrc128WithSeed (const char * s, size_t len, uint128 seed)
Referenced by CityHash128(), and Test().
void CityHashCrc256 (const char * s, size_t len, uint64 * result)
Referenced by CityHash128(), and Test().