automotive-dlt: /home/pfefferz/dlt-daemon/src/tests/dlt-test-stress.c File Reference
dlt-test-stress.c File Reference
#include <netdb.h>
#include <ctype.h>
#include <errno.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include <pthread.h>
#include "dlt.h"
#include "dlt_common.h"
Data Structures
struct thread_data_t
Macros
#define STRESS1_NUM_CONTEXTS 3000
#define STRESS2_MAX_NUM_THREADS 64
#define STRESS3_MAX_NUM_MESSAGES 512
#define MAX_TESTS 3
Functions
void stress1 (void)
void stress2 (void)
void thread_function (void)
void stress3 (void)
void usage ()
int main (int argc, char *argv[])
Variables
DltContext mycontext [9999]
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-test-stress.c.
Macro Definition Documentation
#define MAX_TESTS 3
Definition at line 93 of file dlt-test-stress.c.
Referenced by main().
#define STRESS1_NUM_CONTEXTS 3000
Definition at line 89 of file dlt-test-stress.c.
Referenced by stress1().
#define STRESS2_MAX_NUM_THREADS 64
Definition at line 90 of file dlt-test-stress.c.
Referenced by stress2().
#define STRESS3_MAX_NUM_MESSAGES 512
Definition at line 91 of file dlt-test-stress.c.
Referenced by stress3().
Function Documentation
int main (int argc, char * argv[])
Main function of tool.
Definition at line 125 of file dlt-test-stress.c.
References dlt_init_file(), DLT_REGISTER_APP, DLT_UNREGISTER_APP, MAX_TESTS, stress1(), stress2(), stress3(), and usage().
void stress1 (void)
Definition at line 242 of file dlt-test-stress.c.
References dlt_register_context(), DLT_UNREGISTER_CONTEXT, and STRESS1_NUM_CONTEXTS.
Referenced by main().
void stress2 (void)
Definition at line 284 of file dlt-test-stress.c.
References NULL, thread_data_t::num, STRESS2_MAX_NUM_THREADS, and thread_function().
Referenced by main().
void stress3 (void)
Definition at line 340 of file dlt-test-stress.c.
References buffer, DLT_DECLARE_CONTEXT, DLT_INT, DLT_LOG, DLT_LOG_INFO, DLT_RAW, DLT_REGISTER_CONTEXT, and STRESS3_MAX_NUM_MESSAGES.
Referenced by main().
void thread_function (void)
Definition at line 318 of file dlt-test-stress.c.
References DLT_DECLARE_CONTEXT, DLT_LOG, DLT_LOG_INFO, DLT_REGISTER_CONTEXT, DLT_STRING, and DLT_UNREGISTER_CONTEXT.
Referenced by stress2().
void usage (void)
Print usage information of tool.
Definition at line 105 of file dlt-test-stress.c.
References dlt_get_version().
Referenced by main().
Variable Documentation
DltContext mycontext[9999]
Definition at line 82 of file dlt-test-stress.c.