automotive-dlt: /home/pfefferz/dlt-daemon/src/system/dlt-system.c File Reference
dlt-system.c File Reference
#include "dlt-system.h"
#include <stdio.h>
#include <string.h>
#include <errno.h>
#include <signal.h>
Functions
DLT_DECLARE_CONTEXT (dltsystem)
Detailed Description
Author
Lassi Marttala lassi.nosp@m..lm..nosp@m.martt.nosp@m.ala@.nosp@m.partn.nosp@m.er.b.nosp@m.mw.de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-system.c.
Function Documentation
DLT_DECLARE_CONTEXT (dltsystem)
Definition at line 59 of file dlt-system.c.
References DltSystemConfiguration::ApplicationId, config, DltSystemCliOptions::ConfigurationFileName, DltSystemCliOptions::Daemonize, daemonize(), DLT_LOG, DLT_LOG_DEBUG, DLT_LOG_ERROR, DLT_LOG_FATAL, DLT_LOG_INFO, DLT_REGISTER_APP, DLT_REGISTER_CONTEXT, DLT_STRING, dlt_system_signal_handler(), join_threads(), read_command_line(), read_configuration_file(), and start_threads().