automotive-dlt: /home/pfefferz/dlt-daemon/src/system/dlt-system-processes.c File Reference
dlt-system-processes.c File Reference
#include <pthread.h>
#include <unistd.h>
#include <ctype.h>
#include <sys/types.h>
#include <dirent.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include "dlt-system.h"
Macros
#define SEND_MODE_OFF 0
#define SEND_MODE_ONCE 1
#define SEND_MODE_ON 2
Functions
DLT_IMPORT_CONTEXT (dltsystem)
void logprocess_thread (void *v_conf)
void start_logprocess (DltSystemConfiguration *conf)
Variables
DltSystemThreads threads
Detailed Description
Author
Lassi Marttala lassi.nosp@m..lm..nosp@m.martt.nosp@m.ala@.nosp@m.partn.nosp@m.er.b.nosp@m.mw.de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-system-processes.c.
Macro Definition Documentation
#define SEND_MODE_OFF 0
Definition at line 61 of file dlt-system-processes.c.
Referenced by logprocess_thread().
#define SEND_MODE_ON 2
Definition at line 63 of file dlt-system-processes.c.
#define SEND_MODE_ONCE 1
Definition at line 62 of file dlt-system-processes.c.
Referenced by logprocess_thread().
Function Documentation
DLT_IMPORT_CONTEXT (dltsystem)
Definition at line 67 of file dlt-system-processes.c.
References buffer, DLT_INT, DLT_LOG, DLT_LOG_DEBUG, DLT_LOG_ERROR, DLT_LOG_INFO, DLT_STRING, and NULL.
void logprocess_thread (void * v_conf)
Definition at line 132 of file dlt-system-processes.c.
References LogProcessOptions::ContextId, LogProcessOptions::Count, DLT_LOG, DLT_LOG_DEBUG, DLT_REGISTER_CONTEXT, DLT_STRING, DLT_SYSTEM_LOG_PROCESSES_MAX, DltSystemConfiguration::LogProcesses, LogProcessOptions::Mode, SEND_MODE_OFF, SEND_MODE_ONCE, DltSystemThreads::shutdown, and LogProcessOptions::TimeDelay.
Referenced by start_logprocess().
void start_logprocess (DltSystemConfiguration * conf)
Definition at line 168 of file dlt-system-processes.c.
References DltSystemThreads::count, DLT_LOG, DLT_LOG_DEBUG, DLT_STRING, logprocess_thread(), and DltSystemThreads::threads.
Referenced by start_threads().
Variable Documentation
DltSystemThreads threads
Definition at line 58 of file dlt-system-process-handling.c.