automotive-dlt: /home/pfefferz/dlt-daemon/src/system/dlt-system-options.c File Reference
dlt-system-options.c File Reference
#include "dlt-system.h"
#include <stdlib.h>
#include <string.h>
Functions
void usage (char *prog_name)
void init_cli_options (DltSystemCliOptions *options)
int read_command_line (DltSystemCliOptions *options, int argc, char *argv[])
void init_configuration (DltSystemConfiguration *config)
int read_configuration_file (DltSystemConfiguration *config, char *file_name)
Detailed Description
Author
Lassi Marttala lassi.nosp@m..lm..nosp@m.martt.nosp@m.ala@.nosp@m.partn.nosp@m.er.b.nosp@m.mw.de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-system-options.c.
Function Documentation
void init_cli_options (DltSystemCliOptions * options)
Initialize command line options with default values.
Definition at line 84 of file dlt-system-options.c.
References DltSystemCliOptions::ConfigurationFileName, DltSystemCliOptions::Daemonize, and DEFAULT_CONF_FILE.
Referenced by read_command_line().
void init_configuration (DltSystemConfiguration * config)
Initialize configuration to default values.
Definition at line 133 of file dlt-system-options.c.
References DltSystemConfiguration::ApplicationId, FiletransferOptions::Compression, FiletransferOptions::CompressionLevel, SyslogOptions::ContextId, JournalOptions::ContextId, FiletransferOptions::ContextId, LogFileOptions::ContextId, LogProcessOptions::ContextId, FiletransferOptions::Count, LogFileOptions::Count, LogProcessOptions::Count, JournalOptions::CurrentBoot, FiletransferOptions::Directory, DLT_SYSTEM_LOG_DIRS_MAX, DLT_SYSTEM_LOG_FILE_MAX, DLT_SYSTEM_LOG_PROCESSES_MAX, ShellOptions::Enable, SyslogOptions::Enable, JournalOptions::Enable, FiletransferOptions::Enable, LogFileOptions::Enable, LogProcessOptions::Enable, LogFileOptions::Filename, LogProcessOptions::Filename, DltSystemConfiguration::Filetransfer, JournalOptions::Follow, DltSystemConfiguration::Journal, DltSystemConfiguration::LogFile, DltSystemConfiguration::LogProcesses, JournalOptions::MapLogLevels, LogFileOptions::Mode, LogProcessOptions::Mode, LogProcessOptions::Name, NULL, SyslogOptions::Port, DltSystemConfiguration::Shell, DltSystemConfiguration::Syslog, FiletransferOptions::TimeDelay, LogFileOptions::TimeDelay, LogProcessOptions::TimeDelay, FiletransferOptions::TimeoutBetweenLogs, and FiletransferOptions::TimeStartup.
Referenced by read_configuration_file().
int read_command_line (DltSystemCliOptions * options, int argc, char * argv[])
Read command line options and set the values in provided structure
Definition at line 93 of file dlt-system-options.c.
References DltSystemCliOptions::ConfigurationFileName, DltSystemCliOptions::Daemonize, init_cli_options(), MALLOC_ASSERT, and usage().
int read_configuration_file (DltSystemConfiguration * config, char * file_name)
Read options from the configuration file
Definition at line 196 of file dlt-system-options.c.
References DltSystemConfiguration::ApplicationId, FiletransferOptions::Compression, FiletransferOptions::CompressionLevel, SyslogOptions::ContextId, JournalOptions::ContextId, FiletransferOptions::ContextId, LogFileOptions::ContextId, LogProcessOptions::ContextId, FiletransferOptions::Count, LogFileOptions::Count, LogProcessOptions::Count, JournalOptions::CurrentBoot, FiletransferOptions::Directory, DLT_SYSTEM_LOG_DIRS_MAX, DLT_SYSTEM_LOG_FILE_MAX, DLT_SYSTEM_LOG_PROCESSES_MAX, ShellOptions::Enable, SyslogOptions::Enable, JournalOptions::Enable, FiletransferOptions::Enable, LogFileOptions::Enable, LogProcessOptions::Enable, LogFileOptions::Filename, LogProcessOptions::Filename, DltSystemConfiguration::Filetransfer, JournalOptions::Follow, init_configuration(), DltSystemConfiguration::Journal, DltSystemConfiguration::LogFile, DltSystemConfiguration::LogProcesses, MALLOC_ASSERT, JournalOptions::MapLogLevels, MAX_LINE, LogFileOptions::Mode, LogProcessOptions::Mode, LogProcessOptions::Name, NULL, SyslogOptions::Port, DltSystemConfiguration::Shell, DltSystemConfiguration::Syslog, FiletransferOptions::TempDir, FiletransferOptions::TimeDelay, LogFileOptions::TimeDelay, LogProcessOptions::TimeDelay, FiletransferOptions::TimeoutBetweenLogs, and FiletransferOptions::TimeStartup.
void usage (char * prog_name)
Print information how to use this program.
Definition at line 66 of file dlt-system-options.c.
References DEFAULT_CONF_FILE, and dlt_get_version().
Referenced by read_command_line().