automotive-dlt: /home/pfefferz/dlt-daemon/src/console/dlt-convert.c File Reference
dlt-convert.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <ctype.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/uio.h>
#include "dlt_common.h"
Macros
#define DLT_CONVERT_TEXTBUFSIZE 10024 /* Size of buffer for text output */
Functions
void usage ()
int main (int argc, char *argv[])
Macro Definition Documentation
#define DLT_CONVERT_TEXTBUFSIZE 10024 /* Size of buffer for text output */
Definition at line 91 of file dlt-convert.c.
Referenced by main(), and usage().
Function Documentation
int main (int argc, char * argv[])
Main function of tool.
Definition at line 127 of file dlt-convert.c.
References sDltFile::counter, sDltFile::counter_total, sDltMessage::databuffer, sDltMessage::datasize, DLT_CONVERT_TEXTBUFSIZE, dlt_file_free(), dlt_file_init(), dlt_file_message(), dlt_file_open(), dlt_file_read(), dlt_file_set_filter(), dlt_filter_load(), dlt_message_header(), dlt_message_payload(), dlt_message_print_hex(), dlt_message_print_mixed_plain(), DLT_OUTPUT_ASCII, DLT_RETURN_OK, sDltFile::filter, sDltMessage::headerbuffer, sDltMessage::headersize, sDltFile::msg, and usage().
void usage (void)
Print usage information of tool.
Definition at line 96 of file dlt-convert.c.
References DLT_CONVERT_TEXTBUFSIZE, and dlt_get_version().
Referenced by main().