automotive-dlt: /home/pfefferz/dlt-daemon/src/console/logstorage/dlt-logstorage-prop.h File Reference
dlt-logstorage-prop.h File Reference
Functions
static int dlt_logstorage_prop_init (void)
Initialize proprietary connection.
static int dlt_logstorage_prop_deinit (void)
Clean-up proprietary connection.
static int check_proprietary_handling (char *type)
Check whether user wants to use proprietary handler.
Function Documentation
static int check_proprietary_handling (char * type) inline static
Check whether user wants to use proprietary handler.
Returns
0
Definition at line 46 of file dlt-logstorage-prop.h.
References dlt_logstorage_prop_deinit(), and dlt_logstorage_prop_init().
Referenced by set_handler_type().
static int dlt_logstorage_prop_deinit (void) inline static
Clean-up proprietary connection.
Returns
0
Definition at line 38 of file dlt-logstorage-prop.h.
Referenced by check_proprietary_handling(), and dlt_logstorage_deinit_handler().
static int dlt_logstorage_prop_init (void) inline static
Initialize proprietary connection.
Returns
0
Definition at line 30 of file dlt-logstorage-prop.h.
Referenced by check_proprietary_handling(), and dlt_logstorage_init_handler().