automotive-dlt: /home/pfefferz/dlt-daemon/src/console/logstorage/dlt-logstorage-udev.h File Reference
dlt-logstorage-udev.h File Reference
Functions
int dlt_logstorage_udev_init (void)
Initialize the private data.
int dlt_logstorage_udev_deinit (void)
Clean-up the udev data.
Detailed Description
app begin@ Copyright (C) 2013 - 2015 Advanced Driver Information Technology. This code is developed by Advanced Driver Information Technology. Copyright of Advanced Driver Information Technology, Bosch and DENSO.
This file is part of GENIVI Project Dlt - Diagnostic Log and Trace console apps.
Copyright
This Source Code Form is subject to the terms of the Mozilla Public License, v. 2.0. If a copy of the MPL was not distributed with this file, You can obtain one at http://mozilla.org/MPL/2.0/.
Author
Christoph Lipka clipk.nosp@m.a@jp.nosp@m..adit.nosp@m.-jv..nosp@m.com ADIT 2015
Frederic Berat fbera.nosp@m.t@de.nosp@m..adit.nosp@m.-jv..nosp@m.com ADIT 2015
For further information see http://www.genivi.org/. end@
Definition in file dlt-logstorage-udev.h.
Function Documentation
int dlt_logstorage_udev_deinit (void)
Clean-up the udev data.
Clean-up udev connection
Returns
0 on success, -1 on error
That will destroy all the private data.
Returns
0 on success, -1 otherwise.
Definition at line 340 of file dlt-logstorage-udev.c.
References get_logstorage_control(), lctrl, LogstorageCtrlUdev::mon, NULL, DltLogstorageCtrl::prvt, and LogstorageCtrlUdev::udev.
Referenced by dlt_logstorage_deinit_handler(), and dlt_logstorage_udev_init().
int dlt_logstorage_udev_init (void)
Initialize the private data.
Initialize udev connection
Returns
0 on success, -1 on error
That function will create the udev device and monitor.
Returns
0 on success, -1 otherwise.
Definition at line 374 of file dlt-logstorage-udev.c.
References DltLogstorageCtrl::callback, dlt_logstorage_udev_check_mounted(), dlt_logstorage_udev_deinit(), DltLogstorageCtrl::fd, get_logstorage_control(), lctrl, logstorage_udev_udevd_callback(), LogstorageCtrlUdev::mon, NULL, pr_error, pr_verbose, DltLogstorageCtrl::prvt, and LogstorageCtrlUdev::udev.
Referenced by dlt_logstorage_init_handler().