automotive-dlt: /home/pfefferz/dlt-daemon/src/kpi/dlt-kpi-process.c File Reference
dlt-kpi-process.c File Reference
#include "dlt-kpi-process.h"
#include <pthread.h>
#include <unistd.h>
Functions
DltReturnValue dlt_kpi_read_process_file_to_str (pid_t pid, char **target_str, char *subdir)
unsigned long int dlt_kpi_read_process_stat_to_ulong (pid_t pid, unsigned int index)
DltReturnValue dlt_kpi_read_process_stat_cmdline (pid_t pid, char **buffer)
DltReturnValue dlt_kpi_process_update_io_wait (DltKpiProcess *process, unsigned long int time_dif_ms)
DltReturnValue dlt_kpi_process_update_cpu_time (DltKpiProcess *process, unsigned long int time_dif_ms)
DltReturnValue dlt_kpi_process_update_rss (DltKpiProcess *process)
DltReturnValue dlt_kpi_process_update_ctx_switches (DltKpiProcess *process)
DltReturnValue dlt_kpi_process_update_io_bytes (DltKpiProcess *process)
DltReturnValue dlt_kpi_update_process (DltKpiProcess *process, unsigned long int time_dif_ms)
DltKpiProcess * dlt_kpi_create_process (int pid)
DltKpiProcess * dlt_kpi_clone_process (DltKpiProcess *original)
DltReturnValue dlt_kpi_free_process (DltKpiProcess *process)
DltReturnValue dlt_kpi_print_process (DltKpiProcess *process)
DltReturnValue dlt_kpi_get_msg_process_update (DltKpiProcess *process, char *buffer, int maxlen)
DltReturnValue dlt_kpi_get_msg_process_new (DltKpiProcess *process, char *buffer, int maxlen)
DltReturnValue dlt_kpi_get_msg_process_stop (DltKpiProcess *process, char *buffer, int maxlen)
DltReturnValue dlt_kpi_get_msg_process_commandline (DltKpiProcess *process, char *buffer, int maxlen)
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-kpi-process.c.
Function Documentation
DltKpiProcess* dlt_kpi_clone_process (DltKpiProcess * original)
Definition at line 235 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DltKpiProcess::next, NULL, and DltKpiProcess::prev.
Referenced by dlt_kpi_update_process_list().
DltKpiProcess* dlt_kpi_create_process (int pid)
Definition at line 208 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, dlt_kpi_read_process_file_to_str(), dlt_kpi_read_process_stat_cmdline(), dlt_kpi_read_process_stat_to_ulong(), dlt_kpi_update_process(), NULL, DltKpiProcess::pid, and DltKpiProcess::ppid.
Referenced by dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_free_process (DltKpiProcess * process)
Definition at line 272 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_free_process_list(), and dlt_kpi_remove_process_at_cursor().
DltReturnValue dlt_kpi_get_msg_process_commandline (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 481 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_log_check_commandlines().
DltReturnValue dlt_kpi_get_msg_process_new (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 455 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, DltKpiProcess::pid, and DltKpiProcess::ppid.
Referenced by dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_get_msg_process_stop (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 468 of file dlt-kpi-process.c.
References DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_get_msg_process_update (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 442 of file dlt-kpi-process.c.
References DltKpiProcess::cpu_time, DltKpiProcess::ctx_switches, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::io_bytes, DltKpiProcess::io_wait, NULL, DltKpiProcess::pid, and DltKpiProcess::rss.
Referenced by dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_print_process (DltKpiProcess * process)
Definition at line 288 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DltKpiProcess::cpu_time, DltKpiProcess::ctx_switches, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::io_bytes, DltKpiProcess::io_wait, DltKpiProcess::last_io_wait, NULL, DltKpiProcess::pid, DltKpiProcess::ppid, and DltKpiProcess::rss.
DltReturnValue dlt_kpi_process_update_cpu_time (DltKpiProcess * process, unsigned long int time_dif_ms)
Definition at line 57 of file dlt-kpi-process.c.
References DltKpiProcess::cpu_time, dlt_kpi_get_cpu_count(), dlt_kpi_read_process_stat_to_ulong(), DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::last_cpu_time, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_update_process().
DltReturnValue dlt_kpi_process_update_ctx_switches (DltKpiProcess * process)
Definition at line 99 of file dlt-kpi-process.c.
References buffer, DltKpiProcess::ctx_switches, dlt_kpi_read_process_file_to_str(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_update_process().
DltReturnValue dlt_kpi_process_update_io_bytes (DltKpiProcess * process)
Definition at line 144 of file dlt-kpi-process.c.
References buffer, dlt_kpi_read_process_file_to_str(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::io_bytes, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_update_process().
DltReturnValue dlt_kpi_process_update_io_wait (DltKpiProcess * process, unsigned long int time_dif_ms)
Definition at line 36 of file dlt-kpi-process.c.
References dlt_kpi_get_cpu_count(), dlt_kpi_read_process_stat_to_ulong(), DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::io_wait, DltKpiProcess::last_io_wait, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_update_process().
DltReturnValue dlt_kpi_process_update_rss (DltKpiProcess * process)
Definition at line 86 of file dlt-kpi-process.c.
References dlt_kpi_read_process_stat_to_ulong(), DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, DltKpiProcess::pid, and DltKpiProcess::rss.
Referenced by dlt_kpi_update_process().
DltReturnValue dlt_kpi_read_process_file_to_str (pid_t pid, char ** target_str, char * subdir)
Definition at line 308 of file dlt-kpi-process.c.
References BUFFER_SIZE, dlt_kpi_read_file_compact(), DLT_RETURN_ERROR, and NULL.
Referenced by dlt_kpi_create_process(), dlt_kpi_process_update_ctx_switches(), dlt_kpi_process_update_io_bytes(), dlt_kpi_read_process_stat_cmdline(), and dlt_kpi_read_process_stat_to_ulong().
DltReturnValue dlt_kpi_read_process_stat_cmdline (pid_t pid, char ** buffer)
Definition at line 389 of file dlt-kpi-process.c.
References dlt_kpi_read_process_file_to_str(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_create_process().
unsigned long int dlt_kpi_read_process_stat_to_ulong (pid_t pid, unsigned int index)
Definition at line 336 of file dlt-kpi-process.c.
References buffer, dlt_kpi_read_process_file_to_str(), DLT_RETURN_OK, and NULL.
Referenced by dlt_kpi_create_process(), dlt_kpi_process_update_cpu_time(), dlt_kpi_process_update_io_wait(), and dlt_kpi_process_update_rss().
DltReturnValue dlt_kpi_update_process (DltKpiProcess * process, unsigned long int time_dif_ms)
Definition at line 190 of file dlt-kpi-process.c.
References dlt_kpi_process_update_cpu_time(), dlt_kpi_process_update_ctx_switches(), dlt_kpi_process_update_io_bytes(), dlt_kpi_process_update_io_wait(), dlt_kpi_process_update_rss(), DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_create_process(), and dlt_kpi_update_process_list().