automotive-dlt: /home/pfefferz/dlt-daemon/src/kpi/dlt-kpi-common.h File Reference
dlt-kpi-common.h File Reference
#include <dlt_types.h>
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
Macros
#define BUFFER_SIZE 4096
Functions
DltReturnValue dlt_kpi_read_file (char *filename, char *buffer, uint maxLength)
DltReturnValue dlt_kpi_read_file_compact (char *filename, char **target)
int dlt_kpi_get_cpu_count ()
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-kpi-common.h.
Macro Definition Documentation
#define BUFFER_SIZE 4096
Definition at line 35 of file dlt-kpi-common.h.
Referenced by dlt_kpi_log_interrupts(), dlt_kpi_log_list(), dlt_kpi_read_cpu_count(), dlt_kpi_read_file_compact(), and dlt_kpi_read_process_file_to_str().
Function Documentation
int dlt_kpi_get_cpu_count ()
Definition at line 109 of file dlt-kpi-common.c.
References dlt_kpi_cpu_count, and dlt_kpi_read_cpu_count().
Referenced by dlt_kpi_process_update_cpu_time(), and dlt_kpi_process_update_io_wait().
DltReturnValue dlt_kpi_read_file (char * filename, char * buffer, uint maxLength)
Definition at line 55 of file dlt-kpi-common.c.
References DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_log_interrupts(), dlt_kpi_read_cpu_count(), and dlt_kpi_read_file_compact().
DltReturnValue dlt_kpi_read_file_compact (char * filename, char ** target)
Definition at line 31 of file dlt-kpi-common.c.
References buffer, BUFFER_SIZE, dlt_kpi_read_file(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_read_process_file_to_str().