automotive-dlt: /home/pfefferz/dlt-daemon/src/kpi/dlt-kpi-interrupt.c File Reference
dlt-kpi-interrupt.c File Reference
#include "dlt-kpi-interrupt.h"
Functions
DltReturnValue dlt_kpi_log_interrupts (DltContext *ctx, DltLogLevelType log_level)
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-kpi-interrupt.c.
Function Documentation
DltReturnValue dlt_kpi_log_interrupts (DltContext * ctx, DltLogLevelType log_level)
Definition at line 29 of file dlt-kpi-interrupt.c.
References buffer, BUFFER_SIZE, dlt_kpi_read_file(), DLT_LOG, DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DLT_STRING, dlt_user_log_write_finish(), dlt_user_log_write_start(), dlt_user_log_write_string(), and NULL.
Referenced by dlt_kpi_irq_loop().