automotive-dlt: /home/pfefferz/dlt-daemon/src/system/dlt-system-logfile.c File Reference
dlt-system-logfile.c File Reference
#include <pthread.h>
#include <unistd.h>
#include "dlt-system.h"
Macros
#define SEND_MODE_OFF 0
#define SEND_MODE_ONCE 1
#define SEND_MODE_ON 2
Functions
DLT_IMPORT_CONTEXT (dltsystem)
void register_contexts (LogFileOptions const *fileopts)
void logfile_thread (void *v_conf)
void start_logfile (DltSystemConfiguration *conf)
Detailed Description
Author
Lassi Marttala lassi.nosp@m..lm..nosp@m.martt.nosp@m.ala@.nosp@m.partn.nosp@m.er.b.nosp@m.mw.de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-system-logfile.c.
Macro Definition Documentation
#define SEND_MODE_OFF 0
Definition at line 54 of file dlt-system-logfile.c.
Referenced by logfile_thread().
#define SEND_MODE_ON 2
Definition at line 56 of file dlt-system-logfile.c.
#define SEND_MODE_ONCE 1
Definition at line 55 of file dlt-system-logfile.c.
Referenced by logfile_thread().
Function Documentation
DLT_IMPORT_CONTEXT (dltsystem)
Definition at line 58 of file dlt-system-logfile.c.
References buffer, DLT_INT, DLT_LOG, DLT_LOG_DEBUG, DLT_LOG_ERROR, DLT_LOG_INFO, DLT_STRING, and NULL.
void logfile_thread (void * v_conf)
Definition at line 114 of file dlt-system-logfile.c.
References LogFileOptions::Count, DLT_LOG, DLT_LOG_DEBUG, DLT_STRING, DLT_SYSTEM_LOG_FILE_MAX, DltSystemConfiguration::LogFile, LogFileOptions::Mode, register_contexts(), SEND_MODE_OFF, SEND_MODE_ONCE, DltSystemThreads::shutdown, threads, and LogFileOptions::TimeDelay.
Referenced by start_logfile().
void register_contexts (LogFileOptions const * fileopts)
Definition at line 102 of file dlt-system-logfile.c.
References DLT_LOG, DLT_LOG_DEBUG, DLT_REGISTER_CONTEXT, and DLT_STRING.
Referenced by logfile_thread().
void start_logfile (DltSystemConfiguration * conf)
Definition at line 150 of file dlt-system-logfile.c.
References DltSystemThreads::count, DLT_LOG, DLT_LOG_DEBUG, DLT_STRING, logfile_thread(), threads, and DltSystemThreads::threads.
Referenced by start_threads().