automotive-dlt: /home/pfefferz/dlt-daemon/src/tests/dlt-test-init-free.c File Reference
dlt-test-init-free.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <stdbool.h>
#include "dlt_common.h"
#include "dlt_user.h"
Functions
void exec (const char *cmd, char *buffer, size_t length)
void printMemoryUsage ()
char * occupyMemory (uint size)
void do_example_test ()
void do_dlt_test ()
int main (int argc, char **argv)
Variables
int num_repetitions
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-test-init-free.c.
Function Documentation
void do_dlt_test ()
Definition at line 102 of file dlt-test-init-free.c.
References dlt_free(), dlt_init(), num_repetitions, and printMemoryUsage().
Referenced by main().
void do_example_test ()
Definition at line 61 of file dlt-test-init-free.c.
References occupyMemory(), and printMemoryUsage().
void exec (const char * cmd, char * buffer, size_t length)
Definition at line 114 of file dlt-test-init-free.c.
References NULL.
Referenced by printMemoryUsage().
int main (int argc, char ** argv)
Definition at line 43 of file dlt-test-init-free.c.
References do_dlt_test(), and num_repetitions.
char * occupyMemory (uint size)
Definition at line 140 of file dlt-test-init-free.c.
Referenced by do_example_test().
void printMemoryUsage ()
Definition at line 128 of file dlt-test-init-free.c.
References exec().
Referenced by do_dlt_test(), and do_example_test().
Variable Documentation
int num_repetitions
Definition at line 41 of file dlt-test-init-free.c.
Referenced by do_dlt_test(), and main().