automotive-dlt: /home/pfefferz/dlt-daemon/src/dbus/dlt-dbus-options.c File Reference
dlt-dbus-options.c File Reference
#include "dlt-dbus.h"
#include <stdlib.h>
#include <string.h>
Functions
void usage (char *prog_name)
void init_cli_options (DltDBusCliOptions *options)
int read_command_line (DltDBusCliOptions *options, int argc, char *argv[])
void init_configuration (DltDBusConfiguration *config)
int read_configuration_file (DltDBusConfiguration *config, char *file_name)
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-dbus-options.c.
Function Documentation
void init_cli_options (DltDBusCliOptions * options)
Initialize command line options with default values.
Definition at line 58 of file dlt-dbus-options.c.
References DltDBusCliOptions::ApplicationId, DltDBusCliOptions::BusType, DltDBusCliOptions::ConfigurationFileName, DltDBusCliOptions::Daemonize, and DEFAULT_CONF_FILE.
Referenced by read_command_line().
void init_configuration (DltDBusConfiguration * config)
Initialize configuration to default values.
Definition at line 123 of file dlt-dbus-options.c.
References DltDBusConfiguration::ApplicationId, DBusOptions::BusType, DBusOptions::ContextId, DltDBusConfiguration::DBus, and DBusOptions::FilterCount.
Referenced by read_configuration_file().
int read_command_line (DltDBusCliOptions * options, int argc, char * argv[])
Read command line options and set the values in provided structure
Definition at line 69 of file dlt-dbus-options.c.
References DltDBusCliOptions::ApplicationId, DltDBusCliOptions::BusType, DltDBusCliOptions::ConfigurationFileName, DltDBusCliOptions::Daemonize, init_cli_options(), MALLOC_ASSERT, and usage().
Referenced by DLT_DECLARE_CONTEXT(), and main().
int read_configuration_file (DltDBusConfiguration * config, char * file_name)
Read options from the configuration file
Definition at line 138 of file dlt-dbus-options.c.
References DltDBusConfiguration::ApplicationId, DBusOptions::BusType, DBusOptions::ContextId, DltDBusConfiguration::DBus, DLT_DBUS_FILTER_MAX, DBusOptions::FilterCount, DBusOptions::FilterMatch, init_configuration(), MALLOC_ASSERT, MAX_LINE, and NULL.
Referenced by DLT_DECLARE_CONTEXT(), and main().
void usage (char * prog_name)
Print information how to use this program.
Definition at line 37 of file dlt-dbus-options.c.
References DEFAULT_CONF_FILE, and dlt_get_version().
Referenced by read_command_line().