automotive-dlt: /home/pfefferz/dlt-daemon/src/kpi/dlt-kpi-process.h File Reference
dlt-kpi-process.h File Reference
#include "dlt.h"
#include <stdlib.h>
#include "dlt-kpi-common.h"
Data Structures
struct DltKpiProcess
Typedefs
typedef struct DltKpiEventWatch DltKpiEventWatch
typedef struct DltKpiProcess DltKpiProcess
Functions
DltKpiProcess * dlt_kpi_create_process ()
DltKpiProcess * dlt_kpi_clone_process (DltKpiProcess *original)
DltReturnValue dlt_kpi_free_process (DltKpiProcess *process)
DltReturnValue dlt_kpi_print_process (DltKpiProcess *process)
DltReturnValue dlt_kpi_update_process (DltKpiProcess *process, unsigned long int time_dif_ms)
DltReturnValue dlt_kpi_get_msg_process_new (DltKpiProcess *process, char *buffer, int maxlen)
DltReturnValue dlt_kpi_get_msg_process_stop (DltKpiProcess *process, char *buffer, int maxlen)
DltReturnValue dlt_kpi_get_msg_process_update (DltKpiProcess *process, char *buffer, int maxlen)
DltReturnValue dlt_kpi_get_msg_process_commandline (DltKpiProcess *process, char *buffer, int maxlen)
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-kpi-process.h.
Typedef Documentation
typedef struct DltKpiEventWatch DltKpiEventWatch
Definition at line 34 of file dlt-kpi-process.h.
typedef struct DltKpiProcess DltKpiProcess
Function Documentation
DltKpiProcess* dlt_kpi_clone_process (DltKpiProcess * original)
Definition at line 235 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DltKpiProcess::next, NULL, and DltKpiProcess::prev.
Referenced by dlt_kpi_update_process_list().
DltKpiProcess* dlt_kpi_create_process ()
DltReturnValue dlt_kpi_free_process (DltKpiProcess * process)
Definition at line 272 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_free_process_list(), and dlt_kpi_remove_process_at_cursor().
DltReturnValue dlt_kpi_get_msg_process_commandline (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 481 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_log_check_commandlines().
DltReturnValue dlt_kpi_get_msg_process_new (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 455 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, DltKpiProcess::pid, and DltKpiProcess::ppid.
Referenced by dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_get_msg_process_stop (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 468 of file dlt-kpi-process.c.
References DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and DltKpiProcess::pid.
Referenced by dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_get_msg_process_update (DltKpiProcess * process, char * buffer, int maxlen)
Definition at line 442 of file dlt-kpi-process.c.
References DltKpiProcess::cpu_time, DltKpiProcess::ctx_switches, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::io_bytes, DltKpiProcess::io_wait, NULL, DltKpiProcess::pid, and DltKpiProcess::rss.
Referenced by dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_print_process (DltKpiProcess * process)
Definition at line 288 of file dlt-kpi-process.c.
References DltKpiProcess::command_line, DltKpiProcess::cpu_time, DltKpiProcess::ctx_switches, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::io_bytes, DltKpiProcess::io_wait, DltKpiProcess::last_io_wait, NULL, DltKpiProcess::pid, DltKpiProcess::ppid, and DltKpiProcess::rss.
DltReturnValue dlt_kpi_update_process (DltKpiProcess * process, unsigned long int time_dif_ms)
Definition at line 190 of file dlt-kpi-process.c.
References dlt_kpi_process_update_cpu_time(), dlt_kpi_process_update_ctx_switches(), dlt_kpi_process_update_io_bytes(), dlt_kpi_process_update_io_wait(), dlt_kpi_process_update_rss(), DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_create_process(), and dlt_kpi_update_process_list().