automotive-dlt: /home/pfefferz/dlt-daemon/src/dbus/dlt-dbus.h File Reference
dlt-dbus.h File Reference
#include "dlt.h"
#include "dlt_common.h"
Data Structures
struct DltDBusCliOptions
struct DBusOptions
struct DltDBusConfiguration
Macros
#define DEFAULT_CONF_FILE "/etc/dlt-dbus.conf"
#define DLT_DBUS_FILTER_MAX 32
#define UNUSED(x) (void)(x)
#define MALLOC_ASSERT(x)
#define MAX_LINE 1024
Functions
void init_cli_options (DltDBusCliOptions *options)
int read_command_line (DltDBusCliOptions *options, int argc, char *argv[])
int read_configuration_file (DltDBusConfiguration *config, char *file_name)
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-dbus.h.
Macro Definition Documentation
#define DEFAULT_CONF_FILE "/etc/dlt-dbus.conf"
Definition at line 34 of file dlt-dbus.h.
Referenced by dlt_kpi_init_cli_options(), init_cli_options(), and usage().
#define DLT_DBUS_FILTER_MAX 32
Definition at line 36 of file dlt-dbus.h.
Referenced by read_configuration_file().
#define MALLOC_ASSERT (x)
Value:
if(x == NULL) {\
    fprintf(stderr, "Out of memory\n");\
    abort();}
Definition at line 40 of file dlt-dbus.h.
Referenced by compress_file_to(), flush_dir(), flush_dir_compress(), flush_dir_original(), flush_dir_send(), init_filetransfer_dirs(), read_command_line(), read_configuration_file(), send_one(), and unique_name().
#define MAX_LINE 1024
Definition at line 44 of file dlt-dbus.h.
Referenced by read_configuration_file().
#define UNUSED (x) (void)(x)
Definition at line 39 of file dlt-dbus.h.
Referenced by DLT_DECLARE_CONTEXT().
Function Documentation
void init_cli_options (DltDBusCliOptions * options)
Initialize command line options with default values.
Definition at line 58 of file dlt-dbus-options.c.
References DltDBusCliOptions::ApplicationId, DltDBusCliOptions::BusType, DltDBusCliOptions::ConfigurationFileName, DltDBusCliOptions::Daemonize, and DEFAULT_CONF_FILE.
Referenced by read_command_line().
int read_command_line (DltDBusCliOptions * options, int argc, char * argv[])
Read command line options and set the values in provided structure
Definition at line 69 of file dlt-dbus-options.c.
References DltDBusCliOptions::ApplicationId, DltDBusCliOptions::BusType, DltDBusCliOptions::ConfigurationFileName, DltDBusCliOptions::Daemonize, init_cli_options(), MALLOC_ASSERT, and usage().
Referenced by DLT_DECLARE_CONTEXT(), and main().
int read_configuration_file (DltDBusConfiguration * config, char * file_name)
Read options from the configuration file
Definition at line 138 of file dlt-dbus-options.c.
References DltDBusConfiguration::ApplicationId, DBusOptions::BusType, DBusOptions::ContextId, DltDBusConfiguration::DBus, DLT_DBUS_FILTER_MAX, DBusOptions::FilterCount, DBusOptions::FilterMatch, init_configuration(), MALLOC_ASSERT, MAX_LINE, and NULL.
Referenced by DLT_DECLARE_CONTEXT(), and main().