automotive-dlt: /home/pfefferz/dlt-daemon/src/examples/dlt-example-user.c File Reference
dlt-example-user.c File Reference
#include <netdb.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "dlt.h"
#include "dlt_common.h"
Functions
int dlt_user_injection_callback (uint32_t service_id, void *data, uint32_t length)
void dlt_user_log_level_changed_callback (char context_id[DLT_ID_SIZE], uint8_t log_level, uint8_t trace_status)
DLT_DECLARE_CONTEXT (mycontext)
int main (int argc, char *argv[])
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-example-user.c.
Function Documentation
DLT_DECLARE_CONTEXT (mycontext)
Print usage information of tool.
Definition at line 82 of file dlt-example-user.c.
References dlt_get_version().
int dlt_user_injection_callback (uint32_t service_id, void * data, uint32_t length)
Definition at line 400 of file dlt-example-user.c.
References DLT_LOG, DLT_LOG_INFO, dlt_print_mixed_string(), DLT_STRING, DLT_UINT32, and mycontext.
Referenced by main().
void dlt_user_log_level_changed_callback (char context_id[DLT_ID_SIZE], uint8_t log_level, uint8_t trace_status)
Definition at line 415 of file dlt-example-user.c.
Referenced by main().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 116 of file dlt-example-user.c.
References buffer, DLT_ENABLE_LOCAL_PRINT, DLT_FLOAT32, dlt_get_log_state(), dlt_init_file(), DLT_INT, DLT_LOG, DLT_LOG_ID, DLT_LOG_INFO, DLT_LOG_MARKER, DLT_LOG_WARN, DLT_NONVERBOSE_MODE, DLT_RAW, DLT_REGISTER_APP, DLT_REGISTER_CONTEXT, DLT_REGISTER_INJECTION_CALLBACK, DLT_REGISTER_LOG_LEVEL_CHANGED_CALLBACK, dlt_set_log_mode(), dlt_set_resend_timeout_atexit(), DLT_STRING, DLT_UINT16, DLT_UINT32, DLT_UINT8, DLT_UNREGISTER_APP, DLT_UNREGISTER_CONTEXT, dlt_user_injection_callback(), dlt_user_log_level_changed_callback(), dlt_verbose_mode(), dlt_with_ecu_id(), dlt_with_session_id(), dlt_with_timestamp(), mycontext, and usage().