automotive-dlt: /home/pfefferz/dlt-daemon/src/kpi/dlt-kpi-process-list.h File Reference
dlt-kpi-process-list.h File Reference
#include "dlt-kpi-process.h"
#include "dlt-kpi-common.h"
Data Structures
struct DltKpiProcessList
Functions
DltKpiProcessList * dlt_kpi_create_process_list ()
DltReturnValue dlt_kpi_free_process_list_soft (DltKpiProcessList *list)
DltReturnValue dlt_kpi_free_process_list (DltKpiProcessList *list)
DltKpiProcess * dlt_kpi_get_process_at_cursor (DltKpiProcessList *list)
DltReturnValue dlt_kpi_increment_cursor (DltKpiProcessList *list)
DltReturnValue dlt_kpi_decrement_cursor (DltKpiProcessList *list)
DltReturnValue dlt_kpi_reset_cursor (DltKpiProcessList *list)
DltReturnValue dlt_kpi_add_process_at_start (DltKpiProcessList *list, DltKpiProcess *process)
DltReturnValue dlt_kpi_add_process_before_cursor (DltKpiProcessList *list, DltKpiProcess *process)
DltReturnValue dlt_kpi_add_process_after_cursor (DltKpiProcessList *list, DltKpiProcess *process)
DltReturnValue dlt_kpi_remove_process_at_cursor_soft (DltKpiProcessList *list)
DltReturnValue dlt_kpi_remove_process_at_cursor (DltKpiProcessList *list)
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-kpi-process-list.h.
Function Documentation
DltReturnValue dlt_kpi_add_process_after_cursor (DltKpiProcessList * list, DltKpiProcess * process)
Definition at line 202 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, dlt_kpi_add_process_at_start(), DLT_RETURN_ERROR, DLT_RETURN_OK, DltKpiProcess::next, NULL, and DltKpiProcess::prev.
Referenced by dlt_kpi_add_process_before_cursor(), and dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_add_process_at_start (DltKpiProcessList * list, DltKpiProcess * process)
Definition at line 151 of file dlt-kpi-process-list.c.
References DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::next, NULL, DltKpiProcess::prev, and DltKpiProcessList::start.
Referenced by dlt_kpi_add_process_after_cursor(), and dlt_kpi_add_process_before_cursor().
DltReturnValue dlt_kpi_add_process_before_cursor (DltKpiProcessList * list, DltKpiProcess * process)
Definition at line 168 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, dlt_kpi_add_process_after_cursor(), dlt_kpi_add_process_at_start(), dlt_kpi_set_cursor_at_end(), DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::next, NULL, DltKpiProcess::prev, and DltKpiProcessList::start.
Referenced by dlt_kpi_update_process_list().
DltKpiProcessList* dlt_kpi_create_process_list ()
Definition at line 29 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, NULL, and DltKpiProcessList::start.
Referenced by dlt_kpi_init_process_lists().
DltReturnValue dlt_kpi_decrement_cursor (DltKpiProcessList * list)
Definition at line 135 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and DltKpiProcess::prev.
DltReturnValue dlt_kpi_free_process_list (DltKpiProcessList * list)
Definition at line 57 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, dlt_kpi_free_process(), dlt_kpi_free_process_list_soft(), DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::next, NULL, and DltKpiProcessList::start.
Referenced by dlt_kpi_free_process_lists().
DltReturnValue dlt_kpi_free_process_list_soft (DltKpiProcessList * list)
Definition at line 44 of file dlt-kpi-process-list.c.
References DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_free_process_list().
DltKpiProcess* dlt_kpi_get_process_at_cursor (DltKpiProcessList * list)
Definition at line 78 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, and NULL.
DltReturnValue dlt_kpi_increment_cursor (DltKpiProcessList * list)
Definition at line 119 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::next, and NULL.
Referenced by dlt_kpi_set_cursor_at_end(), and dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_remove_process_at_cursor (DltKpiProcessList * list)
Definition at line 265 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, dlt_kpi_free_process(), dlt_kpi_remove_process_at_cursor_soft(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_log_list(), and dlt_kpi_update_process_list().
DltReturnValue dlt_kpi_remove_process_at_cursor_soft (DltKpiProcessList * list)
Definition at line 223 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiProcess::next, NULL, DltKpiProcess::prev, and DltKpiProcessList::start.
Referenced by dlt_kpi_remove_process_at_cursor().
DltReturnValue dlt_kpi_reset_cursor (DltKpiProcessList * list)
Definition at line 89 of file dlt-kpi-process-list.c.
References DltKpiProcessList::cursor, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and DltKpiProcessList::start.
Referenced by dlt_kpi_log_list(), and dlt_kpi_update_process_list().