automotive-dlt: /home/pfefferz/dlt-daemon/src/system/dlt-system-process-handling.c File Reference
dlt-system-process-handling.c File Reference
#include "dlt.h"
#include "dlt-system.h"
#include <unistd.h>
#include <stdlib.h>
#include <fcntl.h>
#include <signal.h>
#include <sys/wait.h>
#include <pthread.h>
#include <limits.h>
Functions
DLT_IMPORT_CONTEXT (dltsystem)
void start_threads (DltSystemConfiguration *config)
void join_threads ()
void dlt_system_signal_handler (int sig)
Variables
volatile DltSystemThreads threads
Detailed Description
Author
Lassi Marttala lassi.nosp@m..lm..nosp@m.martt.nosp@m.ala@.nosp@m.partn.nosp@m.er.b.nosp@m.mw.de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-system-process-handling.c.
Function Documentation
DLT_IMPORT_CONTEXT (dltsystem)
Close all file descriptors and point stdin, stdout and stderr to /dev/null
Ignore signals related to child processes and terminal handling.
Definition at line 60 of file dlt-system-process-handling.c.
References DLT_LOG, DLT_LOG_DEBUG, and DLT_STRING.
void dlt_system_signal_handler (int sig)
Definition at line 182 of file dlt-system-process-handling.c.
References DLT_INT, DLT_LOG, DLT_LOG_DEBUG, DLT_LOG_WARN, and DLT_STRING.
Referenced by DLT_DECLARE_CONTEXT().
void join_threads ()
Wait for threads to exit. There's not actually a condition currently to bail out of file transfer without a signal.
Definition at line 154 of file dlt-system-process-handling.c.
References DltSystemThreads::count, DLT_INT, DLT_LOG, DLT_LOG_DEBUG, DLT_STRING, NULL, and DltSystemThreads::threads.
Referenced by DLT_DECLARE_CONTEXT().
void start_threads (DltSystemConfiguration * config)
Definition at line 111 of file dlt-system-process-handling.c.
References DltSystemThreads::count, DLT_LOG, DLT_LOG_DEBUG, DLT_STRING, ShellOptions::Enable, SyslogOptions::Enable, JournalOptions::Enable, FiletransferOptions::Enable, LogFileOptions::Enable, LogProcessOptions::Enable, DltSystemConfiguration::Filetransfer, init_shell(), DltSystemConfiguration::Journal, DltSystemConfiguration::LogFile, DltSystemConfiguration::LogProcesses, MAX_THREADS, DltSystemConfiguration::Shell, DltSystemThreads::shutdown, start_filetransfer(), start_logfile(), start_logprocess(), start_syslog(), DltSystemConfiguration::Syslog, and DltSystemThreads::threads.
Referenced by DLT_DECLARE_CONTEXT().
Variable Documentation
volatile DltSystemThreads threads
Definition at line 58 of file dlt-system-process-handling.c.
Referenced by logfile_thread(), and start_logfile().