automotive-dlt: /home/pfefferz/dlt-daemon/src/tests/dlt-test-stress-user.c File Reference
dlt-test-stress-user.c File Reference
#include <stdio.h>
#include <float.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "dlt.h"
Macros
#define DLT_TEST_NUM_CONTEXT 7
Functions
int testall (int count, int repeat, int delay, int size)
DLT_DECLARE_CONTEXT (context_info)
int main (int argc, char *argv[])
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-test-stress-user.c.
Macro Definition Documentation
#define DLT_TEST_NUM_CONTEXT 7
Definition at line 79 of file dlt-test-stress-user.c.
Function Documentation
DLT_DECLARE_CONTEXT (context_info)
Print usage information of tool.
Definition at line 86 of file dlt-test-stress-user.c.
References dlt_get_version().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 122 of file dlt-test-stress-user.c.
References dlt_init_file(), DLT_REGISTER_APP, DLT_REGISTER_CONTEXT, DLT_UNREGISTER_APP, DLT_UNREGISTER_CONTEXT, testall(), and usage().
int testall (int count, int repeat, int delay, int size)
Definition at line 239 of file dlt-test-stress-user.c.
References buffer, DLT_INT, DLT_LOG, DLT_LOG_INFO, and DLT_RAW.
Referenced by main().