automotive-dlt: /home/pfefferz/dlt-daemon/src/examples/dlt-example-user-common-api.c File Reference
dlt-example-user-common-api.c File Reference
#include <netdb.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "dlt_common_api.h"
Functions
DLT_DECLARE_CONTEXT (mycontext)
int main (int argc, char *argv[])
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-example-user-common-api.c.
Function Documentation
DLT_DECLARE_CONTEXT (mycontext)
Print usage information of tool.
Definition at line 66 of file dlt-example-user-common-api.c.
References dlt_get_version().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 97 of file dlt-example-user-common-api.c.
References buffer, DLT_FLOAT32, dlt_get_log_state(), DLT_INT, DLT_LOG2, DLT_LOG_ID0, DLT_LOG_ID1, DLT_LOG_ID2, DLT_LOG_INFO, DLT_LOG_WARN, DLT_RAW, DLT_REGISTER_APP, DLT_REGISTER_CONTEXT_APP, DLT_STRING, DLT_UINT16, DLT_UINT32, DLT_UINT8, DLT_UNREGISTER_APP, DLT_UNREGISTER_CONTEXT, mycontext, and usage().