automotive-dlt: /home/pfefferz/dlt-daemon/src/daemon/dlt-daemon.h File Reference
dlt-daemon.h File Reference
#include <limits.h>
#include "dlt_daemon_common.h"
#include "dlt_user_shared.h"
#include "dlt_user_shared_cfg.h"
#include "dlt_daemon_event_handler_types.h"
#include "dlt_gateway_types.h"
#include <dlt_offline_trace.h>
#include <sys/time.h>
Data Structures
struct DltDaemonFlags
struct DltDaemonLocal
struct DltDaemonPeriodicData
struct DltDaemonTimingPacketThreadData
Macros
#define DLT_DAEMON_FLAG_MAX 256
#define DLT_DAEMON_ERROR_OK 0
#define DLT_DAEMON_ERROR_UNKNOWN -1
#define DLT_DAEMON_ERROR_BUFFER_FULL -2
#define DLT_DAEMON_ERROR_SEND_FAILED -3
#define DLT_DAEMON_ERROR_WRITE_FAILED -4
Typedefs
typedef DltDaemonTimingPacketThreadData DltDaemonECUVersionThreadData
typedef int(* dlt_daemon_process_user_message_func) (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
Functions
void dlt_daemon_local_cleanup (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_local_init_p1 (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_local_init_p2 (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_local_connection_init (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_local_ecu_version_init (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
void dlt_daemon_daemonize (int verbose)
void dlt_daemon_signal_handler (int sig)
int dlt_daemon_process_client_connect (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_client_messages (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *revc, int verbose)
int dlt_daemon_process_client_messages_serial (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_user_messages (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_one_s_timer (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_sixty_s_timer (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_systemd_timer (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_control_connect (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_control_messages (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *recv, int verbose)
int dlt_daemon_process_user_message_overflow (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_send_message_overflow (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_process_user_message_register_application (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_unregister_application (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_register_context (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_unregister_context (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_log (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_set_app_ll_ts (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_marker (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_send_ringbuffer_to_client (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
void dlt_daemon_timingpacket_thread (void *ptr)
void dlt_daemon_ecu_version_thread (void *ptr)
int create_timer_fd (DltDaemonLocal *daemon_local, int period_sec, int starts_in, DltTimers timer)
int dlt_daemon_close_socket (int sock, DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-daemon.h.
Macro Definition Documentation
#define DLT_DAEMON_ERROR_BUFFER_FULL -2
Definition at line 172 of file dlt-daemon.h.
Referenced by dlt_daemon_client_send(), dlt_daemon_log_internal(), and dlt_daemon_process_user_message_log().
#define DLT_DAEMON_ERROR_OK 0
Definition at line 170 of file dlt-daemon.h.
Referenced by dlt_connection_send(), dlt_daemon_client_send(), dlt_daemon_client_send_all_multiple(), dlt_daemon_client_send_control_message(), dlt_daemon_control_message_buffer_overflow(), dlt_daemon_process_user_message_log(), dlt_daemon_send_message_overflow(), dlt_daemon_send_ringbuffer_to_client(), dlt_daemon_serial_send(), dlt_daemon_socket_sendreliable(), and dlt_gateway_process_passive_node_messages().
#define DLT_DAEMON_ERROR_SEND_FAILED -3
Definition at line 173 of file dlt-daemon.h.
Referenced by dlt_daemon_client_send(), dlt_daemon_serial_send(), and dlt_daemon_socket_sendreliable().
#define DLT_DAEMON_ERROR_UNKNOWN -1
Definition at line 171 of file dlt-daemon.h.
Referenced by dlt_connection_send(), dlt_connection_send_multiple(), dlt_daemon_client_send_control_message(), dlt_daemon_control_message_buffer_overflow(), dlt_daemon_process_user_message_log(), dlt_daemon_send_message_overflow(), and dlt_daemon_send_ringbuffer_to_client().
#define DLT_DAEMON_ERROR_WRITE_FAILED -4
Definition at line 174 of file dlt-daemon.h.
#define DLT_DAEMON_FLAG_MAX 256
Definition at line 82 of file dlt-daemon.h.
Typedef Documentation
typedef int(* dlt_daemon_process_user_message_func) (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
Definition at line 196 of file dlt-daemon.h.
typedef DltDaemonTimingPacketThreadData DltDaemonECUVersionThreadData
Definition at line 168 of file dlt-daemon.h.
Function Documentation
void dlt_daemon_ecu_version_thread (void * ptr)
int dlt_daemon_process_one_s_timer (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * recv, int verbose)
Definition at line 1941 of file dlt_daemon_client.c.
References dlt_daemon_control_message_time(), dlt_daemon_send_ringbuffer_to_client(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_STATE_BUFFER_FULL, DLT_DAEMON_STATE_SEND_BUFFER, DLT_DAEMON_STATE_SEND_DIRECT, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DltReceiver::fd, DltDaemonLocal::flags, NULL, PRINT_FUNCTION_VERBOSE, DltDaemon::state, str, DltDaemon::timingpackets, and DltDaemonFlags::vflag.
Referenced by dlt_connection_get_callback().
int dlt_daemon_process_sixty_s_timer (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * recv, int verbose)
Definition at line 2000 of file dlt_daemon_client.c.
References dlt_daemon_control_get_software_version(), dlt_daemon_control_message_timezone(), dlt_daemon_process_systemd_timer(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DltReceiver::fd, DltDaemonLocal::flags, NULL, PRINT_FUNCTION_VERBOSE, DltDaemonFlags::sendECUSoftwareVersion, DltDaemonFlags::sendTimezone, str, and DltDaemonFlags::vflag.
Referenced by dlt_connection_get_callback().
int dlt_daemon_process_systemd_timer (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * recv, int verbose)
Definition at line 2107 of file dlt_daemon_client.c.
References dlt_log().
Referenced by dlt_connection_get_callback(), and dlt_daemon_process_sixty_s_timer().
void dlt_daemon_timingpacket_thread (void * ptr)