automotive-dlt: /home/pfefferz/dlt-daemon/src/kpi/dlt-kpi-common.c File Reference
dlt-kpi-common.c File Reference
#include "dlt-kpi-common.h"
Functions
DltReturnValue dlt_kpi_read_file_compact (char *filename, char **target)
DltReturnValue dlt_kpi_read_file (char *filename, char *buffer, uint maxLength)
int dlt_kpi_read_cpu_count ()
int dlt_kpi_get_cpu_count ()
Variables
static int dlt_kpi_cpu_count = -1
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-kpi-common.c.
Function Documentation
int dlt_kpi_get_cpu_count ()
Definition at line 109 of file dlt-kpi-common.c.
References dlt_kpi_cpu_count, and dlt_kpi_read_cpu_count().
Referenced by dlt_kpi_process_update_cpu_time(), and dlt_kpi_process_update_io_wait().
int dlt_kpi_read_cpu_count ()
Definition at line 78 of file dlt-kpi-common.c.
References buffer, BUFFER_SIZE, dlt_kpi_read_file(), and NULL.
Referenced by dlt_kpi_get_cpu_count().
DltReturnValue dlt_kpi_read_file (char * filename, char * buffer, uint maxLength)
Definition at line 55 of file dlt-kpi-common.c.
References DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_log_interrupts(), dlt_kpi_read_cpu_count(), and dlt_kpi_read_file_compact().
DltReturnValue dlt_kpi_read_file_compact (char * filename, char ** target)
Definition at line 31 of file dlt-kpi-common.c.
References buffer, BUFFER_SIZE, dlt_kpi_read_file(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by dlt_kpi_read_process_file_to_str().
Variable Documentation
int dlt_kpi_cpu_count = -1 static
Definition at line 29 of file dlt-kpi-common.c.
Referenced by dlt_kpi_get_cpu_count().