automotive-dlt: /home/pfefferz/dlt-daemon/src/tests/dlt-test-user.c File Reference
dlt-test-user.c File Reference
#include <stdio.h>
#include <float.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include "dlt.h"
Macros
#define DLT_TEST_NUM_CONTEXT 9
Functions
int test1m (void)
int test2m (void)
int test3m (void)
int test4m (void)
int test5m (void)
int test6m (void)
int test7m (void)
int test8m (void)
int test9m (void)
int test1f (void)
int test2f (void)
int test3f (void)
int test4f (void)
int test5f (void)
int test6f (void)
int test7f (void)
int test8f (void)
int test9f (void)
int test_injection_macro_callback (uint32_t service_id, void *data, uint32_t length)
int test_injection_function_callback (uint32_t service_id, void *data, uint32_t length)
DLT_DECLARE_CONTEXT (context_info)
int main (int argc, char *argv[])
Variables
static const char * loglevelstr [DLT_LOG_MAX]
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-test-user.c.
Macro Definition Documentation
#define DLT_TEST_NUM_CONTEXT 9
Definition at line 79 of file dlt-test-user.c.
Referenced by main().
Function Documentation
DLT_DECLARE_CONTEXT (context_info)
Print usage information of tool.
Definition at line 122 of file dlt-test-user.c.
References dlt_get_version().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 174 of file dlt-test-user.c.
References dlt_init_file(), DLT_LOG, DLT_LOG_INFO, DLT_REGISTER_APP, DLT_REGISTER_CONTEXT, dlt_register_context(), DLT_REGISTER_INJECTION_CALLBACK, dlt_register_injection_callback(), DLT_STRING, DLT_TEST_NUM_CONTEXT, DLT_UNREGISTER_APP, DLT_UNREGISTER_CONTEXT, dlt_unregister_context(), dlt_user_log_write_finish(), dlt_user_log_write_start(), dlt_user_log_write_string(), test1f(), test1m(), test2f(), test2m(), test3f(), test3m(), test4f(), test4m(), test5f(), test5m(), test6f(), test6m(), test7f(), test7m(), test8f(), test8m(), test9f(), test9m(), test_injection_function_callback(), test_injection_macro_callback(), and usage().
int test1f (void)
Definition at line 672 of file dlt-test-user.c.
References DLT_LOG_DEBUG, DLT_LOG_ERROR, DLT_LOG_FATAL, DLT_LOG_INFO, DLT_LOG_VERBOSE, DLT_LOG_WARN, dlt_user_log_write_finish(), dlt_user_log_write_start(), and dlt_user_log_write_string().
Referenced by main().
int test1m (void)
Definition at line 361 of file dlt-test-user.c.
References DLT_LOG, DLT_LOG_DEBUG, DLT_LOG_ERROR, DLT_LOG_FATAL, DLT_LOG_INFO, DLT_LOG_VERBOSE, DLT_LOG_WARN, and DLT_STRING.
Referenced by main().
int test2f (void)
Definition at line 724 of file dlt-test-user.c.
References buffer, DLT_LOG_INFO, dlt_user_log_write_bool(), dlt_user_log_write_finish(), dlt_user_log_write_float32(), dlt_user_log_write_float64(), dlt_user_log_write_int(), dlt_user_log_write_int16(), dlt_user_log_write_int32(), dlt_user_log_write_int64(), dlt_user_log_write_int8(), dlt_user_log_write_raw(), dlt_user_log_write_start(), dlt_user_log_write_string(), dlt_user_log_write_uint(), dlt_user_log_write_uint16(), dlt_user_log_write_uint32(), dlt_user_log_write_uint64(), and dlt_user_log_write_uint8().
Referenced by main().
int test2m (void)
Definition at line 381 of file dlt-test-user.c.
References buffer, DLT_BOOL, DLT_FLOAT32, DLT_FLOAT64, DLT_INT, DLT_INT16, DLT_INT32, DLT_INT64, DLT_INT8, DLT_LOG, DLT_LOG_INFO, DLT_RAW, DLT_STRING, DLT_UINT, DLT_UINT16, DLT_UINT32, DLT_UINT64, DLT_UINT8, and DLT_UTF8.
Referenced by main().
int test3f (void)
Definition at line 844 of file dlt-test-user.c.
References buffer, DLT_LOG_INFO, dlt_nonverbose_mode(), dlt_user_log_write_bool(), dlt_user_log_write_finish(), dlt_user_log_write_float32(), dlt_user_log_write_float64(), dlt_user_log_write_int(), dlt_user_log_write_int16(), dlt_user_log_write_int32(), dlt_user_log_write_int64(), dlt_user_log_write_int8(), dlt_user_log_write_raw(), dlt_user_log_write_start(), dlt_user_log_write_start_id(), dlt_user_log_write_string(), dlt_user_log_write_uint(), dlt_user_log_write_uint16(), dlt_user_log_write_uint32(), dlt_user_log_write_uint64(), dlt_user_log_write_uint8(), and dlt_verbose_mode().
Referenced by main().
int test3m (void)
Definition at line 420 of file dlt-test-user.c.
References buffer, DLT_BOOL, DLT_FLOAT32, DLT_FLOAT64, DLT_INT, DLT_INT16, DLT_INT32, DLT_INT64, DLT_INT8, DLT_LOG, DLT_LOG_ID, DLT_LOG_INFO, DLT_NONVERBOSE_MODE, DLT_RAW, DLT_STRING, DLT_UINT, DLT_UINT16, DLT_UINT32, DLT_UINT64, DLT_UINT8, DLT_UTF8, and DLT_VERBOSE_MODE.
Referenced by main().
int test4f (void)
Definition at line 968 of file dlt-test-user.c.
References buffer, DLT_LOG_INFO, dlt_user_log_write_finish(), dlt_user_log_write_raw(), dlt_user_log_write_start(), and dlt_user_log_write_string().
Referenced by main().
int test4m (void)
Definition at line 463 of file dlt-test-user.c.
References buffer, DLT_LOG, DLT_LOG_INFO, DLT_RAW, and DLT_STRING.
Referenced by main().
int test5f (void)
Definition at line 1022 of file dlt-test-user.c.
References buffer, DLT_LOG_FATAL, DLT_LOG_INFO, dlt_log_int(), DLT_LOG_MAX, dlt_log_raw(), dlt_log_string(), dlt_log_string_int(), dlt_log_string_uint(), dlt_log_uint(), DLT_RETURN_TRUE, DLT_USER_BUF_MAX_SIZE, dlt_user_is_logLevel_enabled(), and loglevelstr.
Referenced by main().
int test5m (void)
Definition at line 489 of file dlt-test-user.c.
References buffer, DLT_IS_LOG_LEVEL_ENABLED, DLT_LOG, DLT_LOG_FATAL, DLT_LOG_INFO, DLT_LOG_INT, DLT_LOG_MAX, DLT_LOG_RAW, DLT_LOG_STRING, DLT_LOG_STRING_INT, DLT_LOG_STRING_UINT, DLT_LOG_UINT, DLT_PTR, DLT_STRING, and loglevelstr.
Referenced by main().
int test6f (void)
Definition at line 1078 of file dlt-test-user.c.
References dlt_disable_local_print(), dlt_enable_local_print(), DLT_LOG_INFO, dlt_user_log_write_finish(), dlt_user_log_write_start(), and dlt_user_log_write_string().
Referenced by main().
int test6m (void)
Definition at line 554 of file dlt-test-user.c.
References DLT_DISABLE_LOCAL_PRINT, DLT_ENABLE_LOCAL_PRINT, DLT_LOG, DLT_LOG_INFO, DLT_LOG_STRING, and DLT_STRING.
Referenced by main().
int test7f (void)
Definition at line 1113 of file dlt-test-user.c.
References buffer, DLT_LOG_DEFAULT, DLT_LOG_INFO, DLT_LOG_VERBOSE, DLT_NW_TRACE_CAN, DLT_NW_TRACE_FLEXRAY, DLT_NW_TRACE_IPC, DLT_NW_TRACE_MOST, dlt_set_application_ll_ts_limit(), DLT_TRACE_STATUS_DEFAULT, DLT_TRACE_STATUS_ON, dlt_user_log_write_finish(), dlt_user_log_write_start(), dlt_user_log_write_string(), and dlt_user_trace_network().
Referenced by main().
int test7m (void)
Definition at line 573 of file dlt-test-user.c.
References buffer, DLT_LOG, DLT_LOG_DEFAULT, DLT_LOG_INFO, DLT_LOG_STRING, DLT_LOG_VERBOSE, DLT_NW_TRACE_CAN, DLT_NW_TRACE_FLEXRAY, DLT_NW_TRACE_IPC, DLT_NW_TRACE_MOST, DLT_SET_APPLICATION_LL_TS_LIMIT, DLT_STRING, DLT_TRACE_NETWORK, DLT_TRACE_STATUS_DEFAULT, and DLT_TRACE_STATUS_ON.
Referenced by main().
int test8f (void)
Definition at line 1154 of file dlt-test-user.c.
References buffer, DLT_LOG_DEFAULT, DLT_LOG_INFO, DLT_LOG_VERBOSE, DLT_NW_TRACE_CAN, DLT_NW_TRACE_FLEXRAY, DLT_NW_TRACE_IPC, DLT_NW_TRACE_MOST, dlt_set_application_ll_ts_limit(), DLT_TRACE_STATUS_DEFAULT, DLT_TRACE_STATUS_ON, dlt_user_log_write_finish(), dlt_user_log_write_start(), dlt_user_log_write_string(), and dlt_user_trace_network_truncated().
Referenced by main().
int test8m (void)
Definition at line 606 of file dlt-test-user.c.
References buffer, DLT_LOG, DLT_LOG_DEFAULT, DLT_LOG_INFO, DLT_LOG_STRING, DLT_LOG_VERBOSE, DLT_NW_TRACE_CAN, DLT_NW_TRACE_FLEXRAY, DLT_NW_TRACE_IPC, DLT_NW_TRACE_MOST, DLT_SET_APPLICATION_LL_TS_LIMIT, DLT_STRING, DLT_TRACE_NETWORK_TRUNCATED, DLT_TRACE_STATUS_DEFAULT, and DLT_TRACE_STATUS_ON.
Referenced by main().
int test9f (void)
Definition at line 1195 of file dlt-test-user.c.
References buffer, DLT_LOG_DEFAULT, DLT_LOG_INFO, DLT_LOG_VERBOSE, DLT_NW_TRACE_CAN, DLT_NW_TRACE_FLEXRAY, DLT_NW_TRACE_IPC, DLT_NW_TRACE_MOST, dlt_set_application_ll_ts_limit(), DLT_TRACE_STATUS_DEFAULT, DLT_TRACE_STATUS_ON, dlt_user_log_write_finish(), dlt_user_log_write_start(), dlt_user_log_write_string(), and dlt_user_trace_network_segmented().
Referenced by main().
int test9m (void)
Definition at line 639 of file dlt-test-user.c.
References buffer, DLT_LOG, DLT_LOG_DEFAULT, DLT_LOG_INFO, DLT_LOG_STRING, DLT_LOG_VERBOSE, DLT_NW_TRACE_CAN, DLT_NW_TRACE_FLEXRAY, DLT_NW_TRACE_IPC, DLT_NW_TRACE_MOST, DLT_SET_APPLICATION_LL_TS_LIMIT, DLT_STRING, DLT_TRACE_NETWORK_SEGMENTED, DLT_TRACE_STATUS_DEFAULT, and DLT_TRACE_STATUS_ON.
Referenced by main().
int test_injection_function_callback (uint32_t service_id, void * data, uint32_t length)
Definition at line 1255 of file dlt-test-user.c.
References DLT_LOG, DLT_LOG_INFO, dlt_print_mixed_string(), DLT_STRING, and DLT_UINT32.
Referenced by main().
int test_injection_macro_callback (uint32_t service_id, void * data, uint32_t length)
Definition at line 1236 of file dlt-test-user.c.
References DLT_LOG, DLT_LOG_INFO, dlt_print_mixed_string(), DLT_STRING, and DLT_UINT32.
Referenced by main().
Variable Documentation
const char* loglevelstr[DLT_LOG_MAX] static
Initial value:
=
{
        "DLT_LOG_OFF",
        "DLT_LOG_FATAL",
        "DLT_LOG_ERROR",
        "DLT_LOG_WARN",
        "DLT_LOG_INFO",
        "DLT_LOG_DEBUG",
        "DLT_LOG_VERBOSE"
}
Definition at line 82 of file dlt-test-user.c.
Referenced by test5f(), and test5m().