automotive-dlt: /home/pfefferz/dlt-daemon/src/tests/dlt-test-filetransfer.c File Reference
dlt-test-filetransfer.c File Reference
#include <dlt_filetransfer.h>
#include <dlt.h>
Functions
DLT_DECLARE_CONTEXT (mainContext)
Declare some context for the main program. It's a must have to do this, when you want to log with dlt.
void printTestResultNegativeExpected (const char *function, int result)
Prints the test result.
int testFile1Run1 ()
Test the file transfer with the condition that the transferred file is smaller as the file transfer buffer using dlt_user_log_file_complete.
int testFile1Run2 ()
Test the file transfer with the condition that the transferred file is smaller as the file transfer buffer using single package transfer.
int testFile2Run1 ()
Test the file transfer with the condition that the transferred file is bigger as the file transfer buffer using dlt_user_log_file_complete.
int testFile2Run2 ()
Test the file transfer with the condition that the transferred file is bigger as the file transfer buffer using single package transfer.
int testFile3Run1 ()
Test the file transfer with the condition that the transferred file does not exist using dlt_user_log_file_complete.
int testFile3Run2 ()
Test the file transfer with the condition that the transferred file does not exist using single package transfer.
int testFile3Run3 ()
Logs some information about the file.
int main (void)
Main program dlt-test-filestransfer starts here.
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-test-filetransfer.c.
Function Documentation
DLT_DECLARE_CONTEXT (mainContext)
Declare some context for the main program. It's a must have to do this, when you want to log with dlt.
Definition at line 62 of file dlt-test-filetransfer.c.
int main (void)
Main program dlt-test-filestransfer starts here.
Definition at line 369 of file dlt-test-filetransfer.c.
References DLT_REGISTER_APP, DLT_REGISTER_CONTEXT, DLT_UNREGISTER_APP, DLT_UNREGISTER_CONTEXT, testFile1Run1(), testFile1Run2(), testFile2Run1(), testFile2Run2(), testFile3Run1(), testFile3Run2(), and testFile3Run3().
void printTestResultNegativeExpected (const char * function, int result)
Prints the test result.
Definition at line 96 of file dlt-test-filetransfer.c.
Referenced by testFile3Run1(), testFile3Run2(), and testFile3Run3().
int testFile1Run1 ()
Test the file transfer with the condition that the transferred file is smaller as the file transfer buffer using dlt_user_log_file_complete.
Definition at line 110 of file dlt-test-filetransfer.c.
References DLT_LOG, DLT_LOG_INFO, DLT_STRING, and dlt_user_log_file_complete().
Referenced by main().
int testFile1Run2 ()
Test the file transfer with the condition that the transferred file is smaller as the file transfer buffer using single package transfer.
Definition at line 130 of file dlt-test-filetransfer.c.
References DLT_LOG, DLT_LOG_INFO, DLT_STRING, dlt_user_check_buffer(), dlt_user_log_file_data(), dlt_user_log_file_end(), dlt_user_log_file_header(), and dlt_user_log_file_packagesCount().
Referenced by main().
int testFile2Run1 ()
Test the file transfer with the condition that the transferred file is bigger as the file transfer buffer using dlt_user_log_file_complete.
Definition at line 193 of file dlt-test-filetransfer.c.
References DLT_LOG, DLT_LOG_INFO, DLT_STRING, and dlt_user_log_file_complete().
Referenced by main().
int testFile2Run2 ()
Test the file transfer with the condition that the transferred file is bigger as the file transfer buffer using single package transfer.
Definition at line 212 of file dlt-test-filetransfer.c.
References DLT_LOG, DLT_LOG_INFO, DLT_STRING, dlt_user_check_buffer(), dlt_user_log_file_data(), dlt_user_log_file_end(), dlt_user_log_file_header(), and dlt_user_log_file_packagesCount().
Referenced by main().
int testFile3Run1 ()
Test the file transfer with the condition that the transferred file does not exist using dlt_user_log_file_complete.
Definition at line 276 of file dlt-test-filetransfer.c.
References DLT_LOG, DLT_LOG_INFO, DLT_STRING, dlt_user_log_file_complete(), and printTestResultNegativeExpected().
Referenced by main().
int testFile3Run2 ()
Test the file transfer with the condition that the transferred file does not exist using single package transfer.
Definition at line 298 of file dlt-test-filetransfer.c.
References DLT_LOG, DLT_LOG_INFO, DLT_STRING, dlt_user_log_file_data(), dlt_user_log_file_end(), dlt_user_log_file_header(), dlt_user_log_file_packagesCount(), and printTestResultNegativeExpected().
Referenced by main().
int testFile3Run3 ()
Logs some information about the file.
Definition at line 348 of file dlt-test-filetransfer.c.
References DLT_LOG, DLT_LOG_INFO, DLT_STRING, dlt_user_log_file_infoAbout(), and printTestResultNegativeExpected().
Referenced by main().