automotive-dlt: /home/pfefferz/dlt-daemon/src/kpi/dlt-kpi-options.c File Reference
dlt-kpi-options.c File Reference
#include "dlt-kpi.h"
Functions
void usage (char *prog_name)
void dlt_kpi_init_cli_options (DltKpiOptions *options)
void dlt_kpi_free_cli_options (DltKpiOptions *options)
DltReturnValue dlt_kpi_read_command_line (DltKpiOptions *options, int argc, char **argv)
void dlt_kpi_init_configuration (DltKpiConfig *config)
DltReturnValue dlt_kpi_read_configuration_file (DltKpiConfig *config, char *file_name)
DltReturnValue dlt_kpi_init (int argc, char **argv, DltKpiConfig *config)
Detailed Description
Author
Sven Hassler sven_.nosp@m.hass.nosp@m.ler@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-kpi-options.c.
Function Documentation
void dlt_kpi_free_cli_options (DltKpiOptions * options)
Definition at line 56 of file dlt-kpi-options.c.
References DltKpiOptions::configurationFileName, and DltKpiOptions::customConfigFile.
Referenced by dlt_kpi_init().
DltReturnValue dlt_kpi_init (int argc, char ** argv, DltKpiConfig * config)
Definition at line 231 of file dlt-kpi-options.c.
References DltKpiOptions::configurationFileName, dlt_kpi_free_cli_options(), dlt_kpi_read_command_line(), dlt_kpi_read_configuration_file(), DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, and NULL.
Referenced by main().
void dlt_kpi_init_cli_options (DltKpiOptions * options)
Initialize command line options with default values.
Definition at line 50 of file dlt-kpi-options.c.
References DltKpiOptions::configurationFileName, DltKpiOptions::customConfigFile, and DEFAULT_CONF_FILE.
Referenced by dlt_kpi_read_command_line().
void dlt_kpi_init_configuration (DltKpiConfig * config)
Initialize configuration to default values.
Definition at line 107 of file dlt-kpi-options.c.
References DLT_LOG_DEFAULT, DltKpiConfig::irq_log_interval, DltKpiConfig::log_level, and DltKpiConfig::process_log_interval.
Referenced by dlt_kpi_read_configuration_file().
DltReturnValue dlt_kpi_read_command_line (DltKpiOptions * options, int argc, char ** argv)
Definition at line 62 of file dlt-kpi-options.c.
References DltKpiOptions::configurationFileName, DltKpiOptions::customConfigFile, dlt_kpi_init_cli_options(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, NULL, and usage().
Referenced by dlt_kpi_init().
DltReturnValue dlt_kpi_read_configuration_file (DltKpiConfig * config, char * file_name)
Read options from the configuration file
Definition at line 117 of file dlt-kpi-options.c.
References DltKpiConfig::check_log_interval, COMMAND_LINE_SIZE, dlt_kpi_init_configuration(), DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_WRONG_PARAMETER, DltKpiConfig::irq_log_interval, DltKpiConfig::log_level, NULL, and DltKpiConfig::process_log_interval.
Referenced by dlt_kpi_init().
void usage (char * prog_name)
Print information how to use this program.
Definition at line 32 of file dlt-kpi-options.c.
References DEFAULT_CONF_FILE, and dlt_get_version().
Referenced by dlt_kpi_read_command_line().