automotive-dlt: /home/pfefferz/dlt-daemon/src/tests/dlt-test-stress-client.c File Reference
dlt-test-stress-client.c File Reference
#include <ctype.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <string.h>
#include <sys/uio.h>
#include "dlt_client.h"
#include "dlt_protocol.h"
#include "dlt_user.h"
Data Structures
struct DltTestclientData
Macros
#define DLT_TESTCLIENT_TEXTBUFSIZE 10024 /* Size of buffer for text output */
#define DLT_TESTCLIENT_ECU_ID "ECU1"
#define DLT_TESTCLIENT_NUM_TESTS 7
Functions
int dlt_testclient_message_callback (DltMessage *message, void *data)
void usage ()
int main (int argc, char *argv[])
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-test-stress-client.c.
Macro Definition Documentation
#define DLT_TESTCLIENT_ECU_ID "ECU1"
Definition at line 82 of file dlt-test-stress-client.c.
Referenced by main().
#define DLT_TESTCLIENT_NUM_TESTS 7
Definition at line 84 of file dlt-test-stress-client.c.
Referenced by main().
#define DLT_TESTCLIENT_TEXTBUFSIZE 10024 /* Size of buffer for text output */
Definition at line 81 of file dlt-test-stress-client.c.
Referenced by dlt_testclient_message_callback().
Function Documentation
int dlt_testclient_message_callback (DltMessage * message, void * data)
10000/(dlt_uptime()-dltdata->time_elapsed)
Definition at line 409 of file dlt-test-stress-client.c.
References DltTestclientData::aflag, DltTestclientData::bytes_received, DltTestclientData::count_not_received_messages, DltTestclientData::count_received_messages, sDltMessage::databuffer, sDltMessage::datasize, DLT_ENDIAN_GET_16, DLT_ENDIAN_GET_32, DLT_GET_MSIN_MSTP, DLT_IS_HTYP_UEH, DLT_IS_HTYP_WEID, DLT_IS_MSIN_VERB, dlt_message_filter_check(), dlt_message_print_header(), dlt_message_print_hex(), dlt_message_print_mixed_plain(), DLT_MSG_READ_VALUE, DLT_RETURN_TRUE, dlt_set_storageheader(), DLT_TESTCLIENT_TEXTBUFSIZE, DLT_TYPE_INFO_RAWD, DLT_TYPE_INFO_SINT, DLT_TYPE_LOG, dlt_uptime(), DltTestclientData::ecuid, sDltMessage::extendedheader, DltTestclientData::filter, DltTestclientData::fvalue, sDltMessage::headerbuffer, sDltMessage::headerextra, sDltMessage::headersize, DltTestclientData::last_value, DltTestclientData::mflag, DltTestclientData::nvalue, DltTestclientData::ohandle, DltTestclientData::ovalue, DltTestclientData::sflag, sDltMessage::standardheader, sDltMessage::storageheader, DltTestclientData::test_counter_macro, DltTestclientData::time_elapsed, DltTestclientData::vflag, and DltTestclientData::xflag.
Referenced by main().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 159 of file dlt-test-stress-client.c.
References DltTestclientData::aflag, DltTestclientData::bvalue, DltTestclientData::bytes_received, DltTestclientData::count_not_received_messages, DltTestclientData::count_received_messages, dlt_client_cleanup(), dlt_client_connect(), dlt_client_init(), dlt_client_main_loop(), dlt_client_register_message_callback(), dlt_client_set_serial_device(), dlt_client_set_server_ip(), dlt_client_setbaudrate(), dlt_file_free(), dlt_file_init(), dlt_file_set_filter(), dlt_filter_free(), dlt_filter_init(), dlt_filter_load(), DLT_RETURN_ERROR, DLT_RETURN_OK, dlt_set_id(), DLT_TESTCLIENT_ECU_ID, dlt_testclient_message_callback(), DLT_TESTCLIENT_NUM_TESTS, dlt_uptime(), DltTestclientData::ecuid, DltTestclientData::evalue, DltTestclientData::file, DltTestclientData::filter, DltTestclientData::fvalue, DltTestclientData::last_value, DltTestclientData::mflag, DltClient::mode, DltTestclientData::nvalue, DltTestclientData::ohandle, DltTestclientData::ovalue, DltTestclientData::running_test, DltClient::serialDevice, DltClient::servIP, DltTestclientData::sflag, DltClient::sock, DltTestclientData::sock, DltTestclientData::test_counter_function, DltTestclientData::test_counter_macro, DltTestclientData::tests_failed, DltTestclientData::tests_passed, DltTestclientData::time_elapsed, usage(), DltTestclientData::vflag, DltTestclientData::xflag, and DltTestclientData::yflag.
void usage (void)
Print usage information of tool.
Definition at line 132 of file dlt-test-stress-client.c.
References dlt_get_version().
Referenced by main().