automotive-dlt: /home/pfefferz/dlt-daemon/src/examples/dlt-example-filetransfer.c File Reference
dlt-example-filetransfer.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <ctype.h>
#include <dlt_filetransfer.h>
#include <dlt.h>
Macros
#define MAXSTRLEN 1024
#define FLTR_APP_DESC "Filetransfer application"
#define FLTR_CONTEXT_DESC "Filetransfer context"
#define FLTR_APP "FLTR"
#define FLTR_CONTEXT "FLTR"
#define TIMEOUT 1
Functions
DLT_DECLARE_CONTEXT (fileContext)
Declare some context for the file transfer. It's not a must have to do this, but later you can set a filter on this context in the dlt viewer.
int main (int argc, char *argv[])
Main program dlt-test-filestransfer starts here.
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-example-filetransfer.c.
Macro Definition Documentation
#define FLTR_APP "FLTR"
Definition at line 70 of file dlt-example-filetransfer.c.
Referenced by main().
#define FLTR_APP_DESC "Filetransfer application"
Definition at line 67 of file dlt-example-filetransfer.c.
Referenced by main().
#define FLTR_CONTEXT "FLTR"
Definition at line 71 of file dlt-example-filetransfer.c.
Referenced by main().
#define FLTR_CONTEXT_DESC "Filetransfer context"
Definition at line 68 of file dlt-example-filetransfer.c.
Referenced by main().
#define MAXSTRLEN 1024
Definition at line 65 of file dlt-example-filetransfer.c.
#define TIMEOUT 1
Definition at line 73 of file dlt-example-filetransfer.c.
Referenced by main().
Function Documentation
DLT_DECLARE_CONTEXT (fileContext)
Declare some context for the file transfer. It's not a must have to do this, but later you can set a filter on this context in the dlt viewer.
Print usage information of tool.
Definition at line 76 of file dlt-example-filetransfer.c.
References dlt_get_version().
int main (int argc, char * argv[])
Main program dlt-test-filestransfer starts here.
Definition at line 103 of file dlt-example-filetransfer.c.
References DLT_ID_SIZE, DLT_REGISTER_APP, DLT_REGISTER_CONTEXT, dlt_set_id(), DLT_UNREGISTER_APP, DLT_UNREGISTER_CONTEXT, dlt_user_log_file_complete(), dlt_user_log_file_infoAbout(), FLTR_APP, FLTR_APP_DESC, FLTR_CONTEXT, FLTR_CONTEXT_DESC, TIMEOUT, and usage().