automotive-dlt: /home/pfefferz/dlt-daemon/src/examples/dlt-example-user-func.c File Reference
dlt-example-user-func.c File Reference
#include <netdb.h>
#include <ctype.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <unistd.h>
#include "dlt.h"
#include "dlt_common.h"
Functions
int dlt_user_injection_callback (uint32_t service_id, void *data, uint32_t length)
void usage ()
int main (int argc, char *argv[])
Variables
DltContext mycontext
DltContextData mycontextdata
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt-example-user-func.c.
Function Documentation
int dlt_user_injection_callback (uint32_t service_id, void * data, uint32_t length)
Definition at line 307 of file dlt-example-user-func.c.
References dlt_print_mixed_string().
Referenced by main().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 107 of file dlt-example-user-func.c.
References dlt_enable_local_print(), dlt_init_file(), DLT_LOG_INFO, DLT_LOG_WARN, dlt_nonverbose_mode(), dlt_register_app(), dlt_register_context(), dlt_register_injection_callback(), dlt_unregister_app(), dlt_unregister_context(), dlt_user_injection_callback(), dlt_user_log_write_finish(), dlt_user_log_write_float32(), dlt_user_log_write_int(), dlt_user_log_write_start(), dlt_user_log_write_start_id(), dlt_user_log_write_string(), dlt_user_log_write_uint16(), dlt_user_log_write_uint32(), dlt_user_log_write_uint8(), and usage().
void usage (void)
Print usage information of tool.
Definition at line 87 of file dlt-example-user-func.c.
References dlt_get_version().
Referenced by main().
Variable Documentation
DltContext mycontext
Definition at line 81 of file dlt-example-user-func.c.
Referenced by DLT_DECLARE_CONTEXT(), dlt_user_injection_callback(), do_logging(), and main().
DltContextData mycontextdata
Definition at line 82 of file dlt-example-user-func.c.