automotive-dlt: /home/pfefferz/dlt-daemon/src/console/dlt-receive.c File Reference
dlt-receive.c File Reference
#include <ctype.h>
#include <stdlib.h>
#include <sys/stat.h>
#include <fcntl.h>
#include <sys/uio.h>
#include <errno.h>
#include <string.h>
#include <glob.h>
#include <syslog.h>
#include <linux/limits.h>
#include <inttypes.h>
#include "dlt_client.h"
Data Structures
struct DltReceiveData
Macros
#define DLT_RECEIVE_TEXTBUFSIZE 10024 /* Size of buffer for text output */
#define DLT_RECEIVE_ECU_ID "RECV"
Functions
int dlt_receive_message_callback (DltMessage *message, void *data)
void usage ()
int64_t convert_arg_to_byte_size (char *arg)
int dlt_receive_open_output_file (DltReceiveData *dltdata)
void dlt_receive_close_output_file (DltReceiveData *dltdata)
int main (int argc, char *argv[])
Macro Definition Documentation
#define DLT_RECEIVE_ECU_ID "RECV"
Definition at line 87 of file dlt-receive.c.
Referenced by main().
#define DLT_RECEIVE_TEXTBUFSIZE 10024 /* Size of buffer for text output */
Definition at line 85 of file dlt-receive.c.
Referenced by dlt_receive_message_callback().
Function Documentation
int64_t convert_arg_to_byte_size (char * arg)
Definition at line 144 of file dlt-receive.c.
References dlt_log(), and sDltMessage::headerbuffer.
Referenced by main().
void dlt_receive_close_output_file (DltReceiveData * dltdata)
Definition at line 289 of file dlt-receive.c.
References DltReceiveData::ohandle.
Referenced by dlt_receive_message_callback().
int dlt_receive_message_callback (DltMessage * message, void * data)
Definition at line 558 of file dlt-receive.c.
References DltReceiveData::aflag, DltReceiveData::climit, sDltMessage::databuffer, sDltMessage::datasize, DLT_IS_HTYP_WEID, dlt_message_filter_check(), dlt_message_header(), dlt_message_payload(), dlt_message_print_hex(), dlt_message_print_mixed_plain(), DLT_OUTPUT_ASCII, dlt_receive_close_output_file(), dlt_receive_open_output_file(), DLT_RECEIVE_TEXTBUFSIZE, DLT_RETURN_TRUE, dlt_set_storageheader(), DltReceiveData::ecuid, DltReceiveData::filter, DltReceiveData::fvalue, sDltMessage::headerbuffer, sDltMessage::headerextra, sDltMessage::headersize, DltReceiveData::mflag, DltReceiveData::ohandle, DltReceiveData::ovalue, DltReceiveData::sflag, sDltMessage::standardheader, sDltMessage::storageheader, DltReceiveData::totalbytes, DltReceiveData::vflag, and DltReceiveData::xflag.
Referenced by main().
int dlt_receive_open_output_file (DltReceiveData * dltdata)
Definition at line 212 of file dlt-receive.c.
References dlt_log(), NULL, DltReceiveData::ohandle, DltReceiveData::ovalue, DltReceiveData::ovaluebase, DltReceiveData::part_num, and DltReceiveData::vflag.
Referenced by dlt_receive_message_callback(), and main().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 302 of file dlt-receive.c.
References DltReceiveData::aflag, DltReceiveData::bvalue, DltReceiveData::climit, convert_arg_to_byte_size(), dlt_client_cleanup(), dlt_client_connect(), dlt_client_init(), dlt_client_main_loop(), DLT_CLIENT_MODE_TCP, dlt_client_register_message_callback(), dlt_client_set_serial_device(), dlt_client_set_server_ip(), dlt_client_setbaudrate(), dlt_file_free(), dlt_file_init(), dlt_file_set_filter(), dlt_filter_free(), dlt_filter_init(), dlt_filter_load(), dlt_log(), DLT_RECEIVE_ECU_ID, dlt_receive_message_callback(), dlt_receive_open_output_file(), DLT_RETURN_ERROR, DLT_RETURN_OK, dlt_set_id(), DltReceiveData::ecuid, DltReceiveData::evalue, DltReceiveData::file, DltReceiveData::filter, DltReceiveData::fvalue, DltReceiveData::mflag, DltClient::mode, DltReceiveData::ohandle, DltReceiveData::ovalue, DltReceiveData::ovaluebase, DltReceiveData::part_num, DltClient::serialDevice, DltClient::servIP, DltReceiveData::sflag, DltReceiveData::totalbytes, usage(), DltReceiveData::vflag, DltReceiveData::xflag, and DltReceiveData::yflag.
void usage (void)
Print usage information of tool.
Definition at line 116 of file dlt-receive.c.
References dlt_get_version().
Referenced by main().