automotive-dlt: /home/pfefferz/dlt-daemon/src/core_dump_handler/dlt_cdh_coredump.c File Reference
dlt_cdh_coredump.c File Reference
#include <stdlib.h>
#include <stdio.h>
#include <string.h>
#include <fcntl.h>
#include <syslog.h>
#include <errno.h>
#include <sys/time.h>
#include <sys/resource.h>
#include <sys/stat.h>
#include "dlt_cdh.h"
Functions
cdh_status_t read_elf_headers (proc_info_t *p_proc)
int getNotePageIndex (proc_info_t *p_proc)
cdh_status_t read_notes (proc_info_t *p_proc)
cdh_status_t init_coredump (proc_info_t *p_proc)
cdh_status_t close_coredump (proc_info_t *p_proc)
cdh_status_t treat_coredump (proc_info_t *p_proc)
Detailed Description
Author
Magneti Marelli http://www.magnetimarelli.com
Lutz Helwing lutz_.nosp@m.helw.nosp@m.ing@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt_cdh_coredump.c.
Function Documentation
cdh_status_t close_coredump (proc_info_t * p_proc)
Definition at line 152 of file dlt_cdh_coredump.c.
References CDH_OK, stream_close(), and proc_info_t::streamer.
Referenced by treat_coredump().
int getNotePageIndex (proc_info_t * p_proc)
Definition at line 69 of file dlt_cdh_coredump.c.
References CDH_NOK, proc_info_t::m_Ehdr, and proc_info_t::m_pPhdr.
Referenced by read_notes().
cdh_status_t init_coredump (proc_info_t * p_proc)
Definition at line 127 of file dlt_cdh_coredump.c.
References proc_info_t::can_create_coredump, CDH_NOK, CDH_OK, CORE_FILE_PATTERN, CORE_MAX_FILENAME_LENGTH, CORE_TMP_DIRECTORY, proc_info_t::name, NULL, proc_info_t::pid, stream_init(), proc_info_t::streamer, and proc_info_t::timestamp.
Referenced by treat_coredump().
cdh_status_t read_elf_headers (proc_info_t * p_proc)
Definition at line 42 of file dlt_cdh_coredump.c.
References CDH_NOK, CDH_OK, ELF_Phdr, proc_info_t::m_Ehdr, proc_info_t::m_pPhdr, NULL, stream_move_to_offest(), stream_read(), and proc_info_t::streamer.
Referenced by treat_coredump().
cdh_status_t read_notes (proc_info_t * p_proc)
Definition at line 90 of file dlt_cdh_coredump.c.
References CDH_NOK, CDH_OK, getNotePageIndex(), proc_info_t::m_Nhdr, proc_info_t::m_note_page_size, proc_info_t::m_pPhdr, NULL, stream_move_to_offest(), stream_read(), and proc_info_t::streamer.
Referenced by treat_coredump().
cdh_status_t treat_coredump (proc_info_t * p_proc)
Definition at line 159 of file dlt_cdh_coredump.c.
References CDH_NOK, CDH_OK, close_coredump(), init_coredump(), read_elf_headers(), read_notes(), stream_finish(), and proc_info_t::streamer.
Referenced by main().