automotive-dlt: /home/pfefferz/dlt-daemon/src/core_dump_handler/dlt_cdh_context.c File Reference
dlt_cdh_context.c File Reference
#include <stdio.h>
#include <string.h>
#include <sys/types.h>
#include <sys/stat.h>
#include <errno.h>
#include <dirent.h>
#include <syslog.h>
#include "dlt_cdh.h"
Macros
#define PROC_FILENAME(x)
Functions
cdh_status_t get_exec_name (unsigned int p_pid, char *p_exec_name, int p_exec_name_maxsize)
cdh_status_t dump_file_to (const char *p_src_filename, FILE *p_fout)
static char ftypelet (mode_t bits)
void strmode (mode_t mode, char *str)
cdh_status_t list_dircontent_to (const char *p_dirname, FILE *p_fout)
cdh_status_t write_proc_context (const proc_info_t *p_proc)
Variables
char g_buffer [4096]
Detailed Description
Author
Magneti Marelli http://www.magnetimarelli.com
Lutz Helwing lutz_.nosp@m.helw.nosp@m.ing@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt_cdh_context.c.
Macro Definition Documentation
#define PROC_FILENAME (x)
Value:
do{\
    snprintf(l_procfile, sizeof(l_procfile), "/proc/%d/"x,\
            p_proc->pid);\
} while(0)
Referenced by write_proc_context().
Function Documentation
cdh_status_t dump_file_to (const char * p_src_filename, FILE * p_fout)
Definition at line 82 of file dlt_cdh_context.c.
References CDH_NOK, CDH_OK, g_buffer, and NULL.
Referenced by write_proc_context().
static char ftypelet (mode_t bits) static
Definition at line 162 of file dlt_cdh_context.c.
Referenced by strmode().
cdh_status_t get_exec_name (unsigned int p_pid, char * p_exec_name, int p_exec_name_maxsize)
Definition at line 52 of file dlt_cdh_context.c.
References CDH_NOK, CDH_OK, CORE_MAX_FILENAME_LENGTH, g_buffer, and NULL.
Referenced by main().
cdh_status_t list_dircontent_to (const char * p_dirname, FILE * p_fout)
Definition at line 240 of file dlt_cdh_context.c.
References CDH_NOK, CDH_OK, CORE_MAX_FILENAME_LENGTH, NULL, and strmode().
Referenced by write_proc_context().
void strmode (mode_t mode, char * str)
Definition at line 202 of file dlt_cdh_context.c.
References ftypelet(), and NULL.
Referenced by list_dircontent_to().
cdh_status_t write_proc_context (const proc_info_t * p_proc)
Definition at line 342 of file dlt_cdh_context.c.
References CDH_NOK, CDH_OK, CONTEXT_FILE_PATTERN, CORE_MAX_FILENAME_LENGTH, CORE_TMP_DIRECTORY, dump_file_to(), list_dircontent_to(), proc_info_t::name, NULL, proc_info_t::pid, PROC_FILENAME, proc_info_t::signal, proc_info_t::threadname, and proc_info_t::timestamp.
Referenced by main().
Variable Documentation
char g_buffer[4096]
Definition at line 39 of file dlt_cdh_context.c.
Referenced by dump_file_to(), and get_exec_name().