automotive-dlt: /home/pfefferz/dlt-daemon/src/daemon/dlt_daemon_socket.h File Reference
dlt_daemon_socket.h File Reference
#include <limits.h>
#include <semaphore.h>
#include "dlt_common.h"
#include "dlt_user.h"
Functions
int dlt_daemon_socket_open (int *sock, unsigned int servPort)
int dlt_daemon_socket_close (int sock)
int dlt_daemon_socket_get_send_qeue_max_size (int sock)
int dlt_daemon_socket_send (int sock, void *data1, int size1, void *data2, int size2, char serialheader)
int dlt_daemon_socket_sendreliable (int sock, void *buffer, int message_size)
dlt_daemon_socket_sendreliable - sends data to socket with additional checks and resending functionality - trying to be reliable
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt_daemon_socket.h.
Function Documentation
int dlt_daemon_socket_close (int sock)
Definition at line 140 of file dlt_daemon_socket.c.
int dlt_daemon_socket_get_send_qeue_max_size (int sock)
Definition at line 206 of file dlt_daemon_socket.c.
Referenced by dlt_daemon_socket_open().
int dlt_daemon_socket_open (int * sock, unsigned int servPort)
Definition at line 66 of file dlt_daemon_socket.c.
References dlt_daemon_socket_get_send_qeue_max_size(), DLT_DAEMON_TEXTBUFSIZE, dlt_log(), dlt_vlog(), NULL, and str.
Referenced by dlt_daemon_local_connection_init().
int dlt_daemon_socket_send (int sock, void * data1, int size1, void * data2, int size2, char serialheader)
Definition at line 147 of file dlt_daemon_socket.c.
References dlt_daemon_socket_sendreliable(), DLT_RETURN_OK, dltSerialHeader, and NULL.
Referenced by dlt_daemon_client_send(), and dlt_daemon_unix_socket_send().
int dlt_daemon_socket_sendreliable (int sock, void * buffer, int message_size)
dlt_daemon_socket_sendreliable - sends data to socket with additional checks and resending functionality - trying to be reliable
Parameters
sock
buffer
message_size
Returns
on sucess: DLT_DAEMON_ERROR_OK, on error: DLT_DAEMON_ERROR_SEND_FAILED
Definition at line 176 of file dlt_daemon_socket.c.
References DLT_DAEMON_ERROR_OK, DLT_DAEMON_ERROR_SEND_FAILED, and dlt_vlog().
Referenced by dlt_connection_send(), and dlt_daemon_socket_send().