automotive-dlt: /home/pfefferz/dlt-daemon/src/shared/dlt_user_shared.h File Reference
dlt_user_shared.h File Reference
#include "dlt_types.h"
#include "dlt_user.h"
#include <sys/types.h>
Data Structures
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
struct PACKED
Functions
DltReturnValue dlt_user_set_userheader (DltUserHeader *userheader, uint32_t mtype)
int dlt_user_check_userheader (DltUserHeader *userheader)
DltReturnValue dlt_user_log_out2 (int handle, void *ptr1, size_t len1, void *ptr2, size_t len2)
DltReturnValue dlt_user_log_out3 (int handle, void *ptr1, size_t len1, void *ptr2, size_t len2, void *ptr3, size_t len3)
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt_user_shared.h.
Function Documentation
int dlt_user_check_userheader (DltUserHeader * userheader)
Check if user header contains its marker
Parameters
userheader pointer to the userheader
Returns
0 no, 1 yes, negative value if there was an error
Definition at line 97 of file dlt_user_shared.c.
Referenced by dlt_daemon_process_user_messages(), dlt_user_log_check_user_message(), and dlt_user_log_resend_buffer().
DltReturnValue dlt_user_log_out2 (int handle, void * ptr1, size_t len1, void * ptr2, size_t len2)
Atomic write to file descriptor, using vector of 2 elements
Parameters
handle file descriptor
ptr1 generic pointer to first segment of data to be written
len1 length of first segment of data to be written
ptr2 generic pointer to second segment of data to be written
len2 length of second segment of data to be written
Returns
Value from DltReturnValue enum
Definition at line 110 of file dlt_user_shared.c.
References DLT_RETURN_ERROR, and DLT_RETURN_OK.
Referenced by dlt_daemon_user_send_log_level(), dlt_daemon_user_send_log_state(), dlt_forward_msg(), dlt_send_app_ll_ts_limit(), dlt_user_log_send_log(), dlt_user_log_send_log_mode(), dlt_user_log_send_marker(), dlt_user_log_send_overflow(), dlt_user_log_send_unregister_application(), and dlt_user_log_send_unregister_context().
DltReturnValue dlt_user_log_out3 (int handle, void * ptr1, size_t len1, void * ptr2, size_t len2, void * ptr3, size_t len3)
Atomic write to file descriptor, using vector of 3 elements
Parameters
handle file descriptor
ptr1 generic pointer to first segment of data to be written
len1 length of first segment of data to be written
ptr2 generic pointer to second segment of data to be written
len2 length of second segment of data to be written
ptr3 generic pointer to third segment of data to be written
len3 length of third segment of data to be written
Returns
Value from DltReturnValue enum
Definition at line 136 of file dlt_user_shared.c.
References DLT_RETURN_ERROR, DLT_RETURN_OK, DLT_RETURN_PIPE_ERROR, and DLT_RETURN_PIPE_FULL.
Referenced by dlt_daemon_control_callsw_cinjection(), dlt_forward_msg(), dlt_user_log_resend_buffer(), dlt_user_log_send_log(), dlt_user_log_send_register_application(), and dlt_user_log_send_register_context().
DltReturnValue dlt_user_set_userheader (DltUserHeader * userheader, uint32_t mtype)
Set user header marker and store message type in user header
Parameters
userheader pointer to the userheader
mtype user message type of internal message
Returns
Value from DltReturnValue enum
Definition at line 80 of file dlt_user_shared.c.
References DLT_RETURN_ERROR, and DLT_RETURN_OK.
Referenced by dlt_daemon_control_callsw_cinjection(), dlt_daemon_user_send_log_level(), dlt_daemon_user_send_log_state(), dlt_forward_msg(), dlt_send_app_ll_ts_limit(), dlt_user_log_send_log(), dlt_user_log_send_log_mode(), dlt_user_log_send_marker(), dlt_user_log_send_overflow(), dlt_user_log_send_register_application(), dlt_user_log_send_register_context(), dlt_user_log_send_unregister_application(), and dlt_user_log_send_unregister_context().