automotive-dlt: /home/pfefferz/dlt-daemon/src/daemon/dlt_daemon_unix_socket.h File Reference
dlt_daemon_unix_socket.h File Reference
Functions
int dlt_daemon_unix_socket_open (int *sock, char *socket_path)
int dlt_daemon_unix_socket_close (int sock)
int dlt_daemon_unix_socket_send (int sock, void *data1, int size1, void *data2, int size2, char serialheader)
Detailed Description
Author
Christoph Lipka clipk.nosp@m.a@jp.nosp@m..adit.nosp@m.-jv..nosp@m.com
Copyright
Copyright © 2015 ADIT.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt_daemon_unix_socket.h.
Function Documentation
int dlt_daemon_unix_socket_close (int sock)
Definition at line 80 of file dlt_daemon_unix_socket.c.
References dlt_log(), and err_string.
int dlt_daemon_unix_socket_open (int * sock, char * socket_path)
Definition at line 43 of file dlt_daemon_unix_socket.c.
References dlt_log(), and NULL.
Referenced by dlt_daemon_local_connection_init().
int dlt_daemon_unix_socket_send (int sock, void * data1, int size1, void * data2, int size2, char serialheader)
Definition at line 93 of file dlt_daemon_unix_socket.c.
References dlt_daemon_socket_send().