automotive-dlt: /home/pfefferz/dlt-daemon/src/daemon/dlt_daemon_common.c File Reference
dlt_daemon_common.c File Reference
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <syslog.h>
#include <errno.h>
#include <unistd.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/socket.h>
#include "dlt_types.h"
#include "dlt_daemon_common.h"
#include "dlt_daemon_common_cfg.h"
#include "dlt_user_shared.h"
#include "dlt_user_shared_cfg.h"
#include "dlt-daemon.h"
#include "dlt_daemon_socket.h"
#include "dlt_daemon_serial.h"
Functions
static int dlt_daemon_cmp_apid (const void *m1, const void *m2)
static int dlt_daemon_cmp_apid_ctid (const void *m1, const void *m2)
int dlt_daemon_init (DltDaemon *daemon, unsigned long RingbufferMinSize, unsigned long RingbufferMaxSize, unsigned long RingbufferStepSize, const char *runtime_directory, int InitialContextLogLevel, int InitialContextTraceStatus, int ForceLLTS, int verbose)
int dlt_daemon_free (DltDaemon *daemon, int verbose)
int dlt_daemon_applications_invalidate_fd (DltDaemon *daemon, int fd, int verbose)
int dlt_daemon_applications_clear (DltDaemon *daemon, int verbose)
DltDaemonApplication * dlt_daemon_application_add (DltDaemon *daemon, char *apid, pid_t pid, char *description, int verbose)
int dlt_daemon_application_del (DltDaemon *daemon, DltDaemonApplication *application, int verbose)
DltDaemonApplication * dlt_daemon_application_find (DltDaemon *daemon, char *apid, int verbose)
int dlt_daemon_applications_load (DltDaemon *daemon, const char *filename, int verbose)
int dlt_daemon_applications_save (DltDaemon *daemon, const char *filename, int verbose)
DltDaemonContext * dlt_daemon_context_add (DltDaemon *daemon, char *apid, char *ctid, int8_t log_level, int8_t trace_status, int log_level_pos, int user_handle, char *description, int verbose)
int dlt_daemon_context_del (DltDaemon *daemon, DltDaemonContext *context, int verbose)
DltDaemonContext * dlt_daemon_context_find (DltDaemon *daemon, char *apid, char *ctid, int verbose)
int dlt_daemon_contexts_invalidate_fd (DltDaemon *daemon, int fd, int verbose)
int dlt_daemon_contexts_clear (DltDaemon *daemon, int verbose)
int dlt_daemon_contexts_load (DltDaemon *daemon, const char *filename, int verbose)
int dlt_daemon_contexts_save (DltDaemon *daemon, const char *filename, int verbose)
int dlt_daemon_configuration_save (DltDaemon *daemon, const char *filename, int verbose)
int dlt_daemon_configuration_load (DltDaemon *daemon, const char *filename, int verbose)
int dlt_daemon_user_send_log_level (DltDaemon *daemon, DltDaemonContext *context, int verbose)
int dlt_daemon_user_send_log_state (DltDaemon *daemon, DltDaemonApplication *app, int verbose)
void dlt_daemon_control_reset_to_factory_default (DltDaemon *daemon, const char *filename, const char *filename1, int InitialContextLogLevel, int InitialContextTraceStatus, int InitialEnforceLlTsStatus, int verbose)
void dlt_daemon_user_send_default_update (DltDaemon *daemon, int verbose)
void dlt_daemon_user_send_all_update (DltDaemon *daemon, int8_t log_level, int verbose)
void dlt_daemon_user_send_all_log_state (DltDaemon *daemon, int verbose)
void dlt_daemon_change_state (DltDaemon *daemon, DltDaemonState newState)
Variables
static char str [DLT_DAEMON_COMMON_TEXTBUFSIZE]
sem_t dlt_daemon_mutex
Detailed Description
Author
Alexander Wenzel alexa.nosp@m.nder.nosp@m..aw.w.nosp@m.enze.nosp@m.l@bmw.nosp@m..de
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt_daemon_common.c.
Function Documentation
static int dlt_daemon_cmp_apid (const void * m1, const void * m2) static
Definition at line 95 of file dlt_daemon_common.c.
References DltDaemonApplication::apid, DLT_ID_SIZE, and NULL.
Referenced by dlt_daemon_application_add(), and dlt_daemon_application_find().
static int dlt_daemon_cmp_apid_ctid (const void * m1, const void * m2) static
Definition at line 106 of file dlt_daemon_common.c.
References DltDaemonContext::apid, DltDaemonContext::ctid, DLT_ID_SIZE, and NULL.
Referenced by dlt_daemon_context_add(), and dlt_daemon_context_find().
Variable Documentation
char str[DLT_DAEMON_COMMON_TEXTBUFSIZE] static
Definition at line 91 of file dlt_daemon_common.c.
Referenced by dlt_daemon_application_add(), dlt_daemon_applications_load(), dlt_daemon_configuration_load(), dlt_daemon_context_add(), dlt_daemon_contexts_load(), and dlt_daemon_init().