automotive-dlt: /home/pfefferz/dlt-daemon/src/core_dump_handler/dlt_cdh_streamer.h File Reference
dlt_cdh_streamer.h File Reference
#include <stdio.h>
#include <zlib.h>
#include "dlt_cdh_definitions.h"
Data Structures
struct file_streamer_t
Functions
cdh_status_t stream_init (file_streamer_t *p_fs, const char *p_src_fname, const char *p_dst_fname)
cdh_status_t stream_close (file_streamer_t *p_fs)
cdh_status_t stream_read (file_streamer_t *p_fs, void *p_buf, unsigned int p_size)
cdh_status_t stream_finish (file_streamer_t *p_fs)
cdh_status_t stream_move_to_offest (file_streamer_t *p_fs, unsigned int p_offset)
cdh_status_t stream_move_ahead (file_streamer_t *p_fs, unsigned int p_nbbytes)
unsigned int stream_get_offset (file_streamer_t *p_fs)
Detailed Description
Author
Magneti Marelli http://www.magnetimarelli.com
Lutz Helwing lutz_.nosp@m.helw.nosp@m.ing@m.nosp@m.ento.nosp@m.r.com
Copyright
Copyright © 2011-2015 BMW AG.
License MPL-2.0: Mozilla Public License version 2.0 http://mozilla.org/MPL/2.0/.
Definition in file dlt_cdh_streamer.h.
Function Documentation
cdh_status_t stream_close (file_streamer_t * p_fs)
Definition at line 93 of file dlt_cdh_streamer.c.
References CDH_NOK, CDH_OK, file_streamer_t::gz_dst_file, NULL, file_streamer_t::read_buf, and file_streamer_t::stream.
Referenced by close_coredump().
cdh_status_t stream_finish (file_streamer_t * p_fs)
Definition at line 153 of file dlt_cdh_streamer.c.
References CDH_NOK, CDH_OK, file_streamer_t::gz_dst_file, NULL, file_streamer_t::offset, file_streamer_t::read_buf, file_streamer_t::stream, and Z_CHUNK_SZ.
Referenced by treat_coredump().
unsigned int stream_get_offset (file_streamer_t * p_fs)
Definition at line 226 of file dlt_cdh_streamer.c.
References CDH_NOK, NULL, and file_streamer_t::offset.
cdh_status_t stream_init (file_streamer_t * p_fs, const char * p_src_fname, const char * p_dst_fname)
Definition at line 38 of file dlt_cdh_streamer.c.
References CDH_NOK, CDH_OK, file_streamer_t::gz_dst_file, NULL, file_streamer_t::read_buf, file_streamer_t::stream, Z_CHUNK_SZ, and Z_MODE_STR.
Referenced by init_coredump().
cdh_status_t stream_move_ahead (file_streamer_t * p_fs, unsigned int p_nbbytes)
Definition at line 194 of file dlt_cdh_streamer.c.
References CDH_NOK, CDH_OK, file_streamer_t::gz_dst_file, NULL, file_streamer_t::offset, file_streamer_t::read_buf, file_streamer_t::stream, and Z_CHUNK_SZ.
Referenced by stream_move_to_offest().
cdh_status_t stream_move_to_offest (file_streamer_t * p_fs, unsigned int p_offset)
Definition at line 179 of file dlt_cdh_streamer.c.
References CDH_NOK, NULL, file_streamer_t::offset, and stream_move_ahead().
Referenced by read_elf_headers(), and read_notes().
cdh_status_t stream_read (file_streamer_t * p_fs, void * p_buf, unsigned int p_size)
Definition at line 123 of file dlt_cdh_streamer.c.
References CDH_NOK, CDH_OK, file_streamer_t::gz_dst_file, NULL, file_streamer_t::offset, and file_streamer_t::stream.
Referenced by read_elf_headers(), and read_notes().