automotive-dlt: DLT Daemon
DLT Daemon
Functions
static int dlt_daemon_log_internal (DltDaemon *daemon, DltDaemonLocal *daemon_local, char *str, int verbose)
void usage ()
int option_handling (DltDaemonLocal *daemon_local, int argc, char *argv[])
int option_file_parser (DltDaemonLocal *daemon_local)
int main (int argc, char *argv[])
int dlt_daemon_local_init_p1 (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_local_init_p2 (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
static int dlt_daemon_init_serial (DltDaemonLocal *daemon_local)
static int dlt_daemon_init_fifo (DltDaemonLocal *daemon_local)
int dlt_daemon_local_connection_init (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_local_ecu_version_init (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
void dlt_daemon_local_cleanup (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
void dlt_daemon_signal_handler (int sig)
void dlt_daemon_daemonize (int verbose)
int dlt_daemon_process_client_connect (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *receiver, int verbose)
int dlt_daemon_process_client_messages (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *receiver, int verbose)
int dlt_daemon_process_client_messages_serial (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *receiver, int verbose)
int dlt_daemon_process_control_connect (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *receiver, int verbose)
int dlt_daemon_process_control_messages (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *receiver, int verbose)
static int dlt_daemon_process_user_message_not_sup (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *receiver, int verbose)
int dlt_daemon_process_user_messages (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *receiver, int verbose)
int dlt_daemon_process_user_message_overflow (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_send_message_overflow (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int dlt_daemon_process_user_message_register_application (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_register_context (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_unregister_application (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_unregister_context (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_log (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_set_app_ll_ts (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_log_mode (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_process_user_message_marker (DltDaemon *daemon, DltDaemonLocal *daemon_local, DltReceiver *rec, int verbose)
int dlt_daemon_send_ringbuffer_to_client (DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
int create_timer_fd (DltDaemonLocal *daemon_local, int period_sec, int starts_in, DltTimers timer_id)
int dlt_daemon_close_socket (int sock, DltDaemon *daemon, DltDaemonLocal *daemon_local, int verbose)
Variables
static char str [DLT_DAEMON_TEXTBUFSIZE]
int g_exit = 0
static dlt_daemon_process_user_message_func process_user_func [DLT_USER_MESSAGE_NOT_SUPPORTED]
static char dlt_timer_conn_types [DLT_TIMER_UNKNOWN+1]
static char dlt_timer_names [DLT_TIMER_UNKNOWN+1][32]
Detailed Description
Function Documentation
int create_timer_fd (DltDaemonLocal * daemon_local, int period_sec, int starts_in, DltTimers timer_id)
Definition at line 3142 of file dlt-daemon.c.
References dlt_connection_create(), dlt_log(), DLT_LOG_ERROR, dlt_timer_conn_types, dlt_timer_names, DLT_TIMER_UNKNOWN, NULL, DltDaemonLocal::pEvent, and str.
Referenced by main().
int dlt_daemon_close_socket (int sock, DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 3222 of file dlt-daemon.c.
References DltDaemonLocal::client_connections, DltDaemon::connectionState, DLT_CONNECTION_STATUS_DISCONNECTED, dlt_daemon_change_state(), dlt_daemon_control_message_connection_info(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_STATE_BUFFER, DLT_DAEMON_TEXTBUFSIZE, dlt_daemon_user_send_all_log_state(), dlt_event_handler_unregister_connection(), dlt_log(), DltDaemonLocal::flags, NULL, DltDaemonLocal::pEvent, PRINT_FUNCTION_VERBOSE, str, DltDaemonFlags::vflag, and DltDaemonFlags::yvalue.
Referenced by dlt_daemon_client_send_all_multiple(), dlt_daemon_process_client_messages(), and dlt_daemon_process_control_messages().
void dlt_daemon_daemonize (int verbose)
Definition at line 1288 of file dlt-daemon.c.
References DLT_DAEMON_LOCK_FILE, DLT_DAEMON_LOCK_FILE_PERM, DLT_DAEMON_TEXTBUFSIZE, DLT_DAEMON_UMASK, dlt_log(), dltFifoBaseDir, PRINT_FUNCTION_VERBOSE, and str.
Referenced by dlt_daemon_local_init_p1().
static int dlt_daemon_init_fifo (DltDaemonLocal * daemon_local) static
Definition at line 996 of file dlt-daemon.c.
References DltDaemonFlags::daemonFifoName, DltDaemonLocal::daemonFifoSize, DLT_CONNECTION_APP_MSG, dlt_connection_create(), DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DltDaemonLocal::flags, DltDaemonLocal::pEvent, and str.
Referenced by dlt_daemon_local_connection_init().
static int dlt_daemon_init_serial (DltDaemonLocal * daemon_local) static
Definition at line 924 of file dlt-daemon.c.
References DltDaemonLocal::baudrate, DltDaemonFlags::bvalue, DLT_CONNECTION_CLIENT_MSG_SERIAL, dlt_connection_create(), dlt_convert_serial_speed(), DLT_DAEMON_SERIAL_DEFAULT_BAUDRATE, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), dlt_setup_serial(), DltDaemonLocal::flags, DltDaemonLocal::pEvent, str, DltDaemonFlags::vflag, and DltDaemonFlags::yvalue.
Referenced by dlt_daemon_local_connection_init().
void dlt_daemon_local_cleanup (DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 1200 of file dlt-daemon.c.
References DltDaemonFlags::ctrlSockPath, DltDaemonFlags::daemonFifoName, DLT_DAEMON_LOCK_FILE, dlt_daemon_logstorage_cleanup(), dlt_event_handler_cleanup_connections(), dlt_file_free(), dlt_log(), dlt_message_free(), dlt_offline_trace_free(), dlt_shm_free_server(), DltDaemon::ECUVersionString, DltDaemonLocal::file, DltDaemonLocal::flags, DltDaemonLocal::msg, NULL, DltDaemonFlags::offlineLogstorageMaxDevices, DltDaemonLocal::offlineTrace, DltDaemonFlags::offlineTraceDirectory, DltDaemonLocal::pEvent, PRINT_FUNCTION_VERBOSE, DltDaemon::storage_handle, and DltDaemonFlags::vflag.
Referenced by main().
int dlt_daemon_local_connection_init (DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 1067 of file dlt-daemon.c.
References DltDaemonLocal::client_connections, DltDaemonFlags::ctrlSockPath, DLT_CONNECTION_CLIENT_CONNECT, DLT_CONNECTION_CONTROL_CONNECT, dlt_connection_create(), dlt_daemon_init_fifo(), dlt_daemon_init_serial(), dlt_daemon_socket_open(), DLT_DAEMON_TEXTBUFSIZE, dlt_daemon_unix_socket_open(), dlt_log(), DltDaemonLocal::flags, NULL, DltDaemonLocal::pEvent, DltDaemonFlags::port, and PRINT_FUNCTION_VERBOSE.
Referenced by main().
int dlt_daemon_local_ecu_version_init (DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 1128 of file dlt-daemon.c.
References DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DltDaemon::ECUVersionString, DltDaemonLocal::flags, NULL, DltDaemonFlags::pathToECUSoftwareVersion, and PRINT_FUNCTION_VERBOSE.
Referenced by dlt_daemon_local_init_p2().
int dlt_daemon_local_init_p1 (DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 748 of file dlt-daemon.c.
References DltDaemonFlags::dflag, dlt_daemon_daemonize(), dlt_daemon_signal_handler(), DLT_DAEMON_TEXTBUFSIZE, dlt_file_free(), dlt_file_init(), dlt_log(), DLT_RETURN_ERROR, DltDaemonLocal::file, DltDaemonLocal::flags, PRINT_FUNCTION_VERBOSE, str, DltDaemonFlags::userPipesDir, and DltDaemonFlags::vflag.
Referenced by main().
int dlt_daemon_local_init_p2 (DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 823 of file dlt-daemon.c.
References DltDaemonFlags::contextLogLevel, DltDaemonFlags::contextTraceStatus, DLT_DAEMON_ECU_ID, dlt_daemon_init(), dlt_daemon_local_ecu_version_init(), dlt_daemon_mutex, DLT_DAEMON_TEXTBUFSIZE, dlt_get_version(), dlt_log(), dlt_message_init(), dlt_offline_trace_init(), DLT_RETURN_ERROR, dlt_set_id(), dlt_shm_init_server(), DLT_SHM_KEY, DLT_USER_MODE_BOTH, DLT_USER_MODE_INTERNAL, DltDaemon::ecuid, DltDaemon::ECUVersionString, DltDaemonFlags::enforceContextLLAndTS, DltDaemonFlags::evalue, DltDaemonLocal::flags, DltDaemonFlags::ivalue, DltDaemonFlags::lflag, DltDaemon::mode, DltDaemonLocal::msg, NULL, DltDaemonFlags::offlineLogstorageMaxDevices, DltDaemonLocal::offlineTrace, DltDaemonFlags::offlineTraceDirectory, DltDaemonFlags::offlineTraceFilenameTimestampBased, DltDaemonFlags::offlineTraceFileSize, DltDaemonFlags::offlineTraceMaxSize, PRINT_FUNCTION_VERBOSE, DltDaemonLocal::RingbufferMaxSize, DltDaemonLocal::RingbufferMinSize, DltDaemonLocal::RingbufferStepSize, DltDaemonFlags::sendMessageTime, DltDaemon::sendserialheader, DltDaemonFlags::sharedMemorySize, DltDaemon::storage_handle, DltDaemon::timingpackets, and DltDaemonFlags::vflag.
Referenced by main().
int dlt_daemon_log_internal (DltDaemon * daemon, DltDaemonLocal * daemon_local, char * str, int verbose) static
Definition at line 1383 of file dlt-daemon.c.
References sDltMessage::databuffer, sDltMessage::databuffersize, sDltMessage::datasize, dlt_daemon_client_send(), DLT_DAEMON_ERROR_BUFFER_FULL, dlt_daemon_send_message_overflow(), DLT_DAEMON_SEND_TO_ALL, DLT_HTOBE_16, DLT_HTOBE_32, DLT_HTYP_PROTOCOL_VERSION1, DLT_HTYP_UEH, DLT_HTYP_WEID, DLT_HTYP_WSID, DLT_HTYP_WTMS, DLT_IS_HTYP_UEH, dlt_log(), DLT_LOG_INFO, DLT_MSIN_MSTP_SHIFT, DLT_MSIN_MTIN, DLT_MSIN_MTIN_SHIFT, DLT_MSIN_VERB, dlt_set_id(), dlt_set_storageheader(), DLT_STANDARD_HEADER_EXTRA_SIZE, DLT_TYPE_INFO_STRG, DLT_TYPE_LOG, dlt_uptime(), DLT_USER_MODE_BOTH, DLT_USER_MODE_EXTERNAL, DltDaemon::ecuid, sDltMessage::extendedheader, sDltMessage::headerbuffer, sDltMessage::headersize, DltDaemon::mode, DltDaemon::overflow_counter, PRINT_FUNCTION_VERBOSE, sDltMessage::standardheader, and sDltMessage::storageheader.
Referenced by dlt_daemon_process_user_message_register_application(), dlt_daemon_process_user_message_register_context(), dlt_daemon_process_user_message_unregister_application(), dlt_daemon_process_user_message_unregister_context(), and main().
int dlt_daemon_process_client_connect (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * receiver, int verbose)
Definition at line 1477 of file dlt-daemon.c.
References DltDaemonLocal::client_connections, DltDaemon::connectionState, DLT_CONNECTION_CLIENT_MSG_TCP, dlt_connection_create(), DLT_CONNECTION_STATUS_CONNECTED, dlt_daemon_applications_invalidate_fd(), dlt_daemon_change_state(), dlt_daemon_contexts_invalidate_fd(), dlt_daemon_control_get_software_version(), dlt_daemon_control_message_connection_info(), dlt_daemon_control_message_timezone(), dlt_daemon_send_ringbuffer_to_client(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_STATE_SEND_BUFFER, DLT_DAEMON_TEXTBUFSIZE, dlt_daemon_user_send_all_log_state(), dlt_log(), DltReceiver::fd, DltDaemonLocal::flags, NULL, DltDaemonLocal::pEvent, PRINT_FUNCTION_VERBOSE, DltDaemonFlags::sendECUSoftwareVersion, DltDaemonFlags::sendTimezone, str, DltDaemonLocal::timeoutOnSend, and DltDaemonFlags::vflag.
Referenced by dlt_connection_get_callback().
int dlt_daemon_process_client_messages (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * receiver, int verbose)
Definition at line 1593 of file dlt-daemon.c.
References DltReceiver::buf, DltReceiver::bytesRcvd, sDltMessage::datasize, dlt_daemon_client_process_control(), dlt_daemon_close_socket(), dlt_log(), DLT_MESSAGE_ERROR_OK, dlt_message_read(), DLT_MSG_IS_CONTROL_REQUEST, dlt_receiver_move_to_begin(), dlt_receiver_receive_socket(), dlt_receiver_remove(), dltSerialHeader, DltReceiver::fd, DltDaemonLocal::flags, sDltMessage::found_serialheader, sDltMessage::headersize, DltDaemonLocal::msg, DltDaemonFlags::nflag, NULL, PRINT_FUNCTION_VERBOSE, sDltMessage::resync_offset, and DltDaemonFlags::vflag.
Referenced by dlt_connection_get_callback().
int dlt_daemon_process_client_messages_serial (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * receiver, int verbose)
Definition at line 1681 of file dlt-daemon.c.
References DltReceiver::buf, DltReceiver::bytesRcvd, sDltMessage::datasize, dlt_daemon_client_process_control(), dlt_log(), DLT_MESSAGE_ERROR_OK, dlt_message_read(), DLT_MSG_IS_CONTROL_REQUEST, dlt_receiver_move_to_begin(), dlt_receiver_receive_fd(), dlt_receiver_remove(), dltSerialHeader, DltReceiver::fd, DltDaemonLocal::flags, sDltMessage::found_serialheader, sDltMessage::headersize, DltDaemonFlags::mflag, DltDaemonLocal::msg, NULL, PRINT_FUNCTION_VERBOSE, sDltMessage::resync_offset, and DltDaemonFlags::vflag.
Referenced by dlt_connection_get_callback().
int dlt_daemon_process_control_connect (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * receiver, int verbose)
Definition at line 1761 of file dlt-daemon.c.
References DLT_CONNECTION_CONTROL_MSG, dlt_connection_create(), dlt_daemon_applications_invalidate_fd(), dlt_daemon_contexts_invalidate_fd(), DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DltReceiver::fd, NULL, DltDaemonLocal::pEvent, PRINT_FUNCTION_VERBOSE, and str.
Referenced by dlt_connection_get_callback().
int dlt_daemon_process_control_messages (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * receiver, int verbose)
Definition at line 1817 of file dlt-daemon.c.
References DltReceiver::buf, DltReceiver::bytesRcvd, sDltMessage::datasize, dlt_daemon_client_process_control(), dlt_daemon_close_socket(), dlt_log(), DLT_MESSAGE_ERROR_OK, dlt_message_read(), DLT_MSG_IS_CONTROL_REQUEST, dlt_receiver_move_to_begin(), dlt_receiver_receive_socket(), dlt_receiver_remove(), dltSerialHeader, DltReceiver::fd, DltDaemonLocal::flags, sDltMessage::found_serialheader, sDltMessage::headersize, DltDaemonLocal::msg, DltDaemonFlags::nflag, NULL, PRINT_FUNCTION_VERBOSE, sDltMessage::resync_offset, and DltDaemonFlags::vflag.
Referenced by dlt_connection_get_callback().
int dlt_daemon_process_user_message_log (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2618 of file dlt-daemon.c.
References DltDaemonFlags::aflag, DltReceiver::buf, DltReceiver::bytesRcvd, sDltMessage::databuffer, sDltMessage::datasize, DLT_BETOH_32, dlt_daemon_client_send(), dlt_daemon_client_send_all(), DLT_DAEMON_ECU_ID, DLT_DAEMON_ERROR_BUFFER_FULL, DLT_DAEMON_ERROR_OK, DLT_DAEMON_ERROR_UNKNOWN, dlt_daemon_send_message_overflow(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_TEXTBUFSIZE, DLT_DAEMON_TEXTSIZE, DLT_IS_HTYP_WEID, dlt_log(), DLT_MESSAGE_ERROR_OK, DLT_MESSAGE_ERROR_SIZE, dlt_message_print_ascii(), dlt_message_print_header(), dlt_message_print_hex(), dlt_message_read(), dlt_message_set_extraparameters(), dlt_offline_trace_write(), DLT_RCV_REMOVE, dlt_receiver_check_and_get(), dlt_receiver_remove(), DLT_RETURN_ERROR, dlt_set_id(), dlt_set_storageheader(), dlt_shm_copy(), dlt_shm_remove(), DLT_USER_MESSAGE_LOG_SHM, dltSerialHeader, DltDaemon::ecuid, DltDaemonFlags::evalue, DltDaemonLocal::flags, sDltMessage::found_serialheader, sDltMessage::headerbuffer, sDltMessage::headerextra, sDltMessage::headersize, DltDaemonLocal::msg, NULL, DltDaemonLocal::offlineTrace, DltDaemonFlags::offlineTraceDirectory, DltDaemon::overflow_counter, PRINT_FUNCTION_VERBOSE, DltDaemonFlags::sflag, sDltMessage::standardheader, sDltMessage::storageheader, str, and DltDaemonFlags::xflag.
int dlt_daemon_process_user_message_log_mode (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2992 of file dlt-daemon.c.
References dlt_daemon_configuration_save(), dlt_log(), DLT_RCV_REMOVE, DLT_RCV_SKIP_HEADER, dlt_receiver_check_and_get(), DltDaemon::mode, PRINT_FUNCTION_VERBOSE, and DltDaemon::runtime_configuration.
int dlt_daemon_process_user_message_marker (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 3027 of file dlt-daemon.c.
References dlt_daemon_control_message_marker(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), dlt_receiver_check_and_get(), NULL, and PRINT_FUNCTION_VERBOSE.
static int dlt_daemon_process_user_message_not_sup (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * receiver, int verbose) static
Definition at line 1897 of file dlt-daemon.c.
References DltReceiver::buf, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), dlt_receiver_remove(), and PRINT_FUNCTION_VERBOSE.
Referenced by dlt_daemon_process_user_messages().
int dlt_daemon_process_user_message_overflow (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2035 of file dlt-daemon.c.
References dlt_daemon_control_message_buffer_overflow(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DLT_RCV_REMOVE, DLT_RCV_SKIP_HEADER, dlt_receiver_check_and_get(), NULL, DltDaemon::overflow_counter, and PRINT_FUNCTION_VERBOSE.
int dlt_daemon_process_user_message_register_application (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2103 of file dlt-daemon.c.
References DltDaemonApplication::apid, DltDaemonApplication::application_description, DltReceiver::buf, dlt_daemon_application_add(), DLT_DAEMON_DESCSIZE, dlt_daemon_log_internal(), DLT_DAEMON_TEXTBUFSIZE, dlt_daemon_user_send_log_state(), dlt_log(), DLT_RCV_NONE, DLT_RCV_SKIP_HEADER, dlt_receiver_check_and_get(), dlt_receiver_remove(), DLT_RETURN_OK, DltDaemonLocal::flags, NULL, DltDaemonApplication::pid, PRINT_FUNCTION_VERBOSE, and DltDaemonFlags::vflag.
int dlt_daemon_process_user_message_register_context (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2213 of file dlt-daemon.c.
References DltDaemonContext::apid, DltDaemonFlags::autoResponseGetLogInfoOption, DltReceiver::buf, DltDaemonContext::context_description, DltDaemonContext::ctid, sDltMessage::databuffer, sDltMessage::databuffersize, sDltMessage::datasize, dlt_daemon_application_find(), dlt_daemon_context_add(), dlt_daemon_control_get_log_info(), DLT_DAEMON_DESCSIZE, dlt_daemon_log_internal(), dlt_daemon_logstorage_get_loglevel(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_TEXTBUFSIZE, dlt_daemon_user_send_log_level(), DLT_FD_MINIMUM, dlt_log(), DLT_LOG_DEFAULT, DLT_LOG_VERBOSE, dlt_message_free(), dlt_message_init(), DLT_RCV_NONE, DLT_RCV_SKIP_HEADER, dlt_receiver_check_and_get(), dlt_receiver_remove(), DLT_RETURN_OK, DLT_SERVICE_ID_GET_LOG_INFO, dlt_set_id(), DLT_TRACE_STATUS_DEFAULT, DLT_TRACE_STATUS_ON, DLT_USER_LOG_LEVEL_NOT_SET, DLT_USER_TRACE_STATUS_NOT_SET, dlt_vlog(), DltDaemonLocal::flags, NULL, DltDaemonFlags::offlineLogstorageMaxDevices, PRINT_FUNCTION_VERBOSE, DltDaemonFlags::rflag, DltDaemonContext::storage_log_level, DltDaemonApplication::user_handle, and DltDaemonContext::user_handle.
int dlt_daemon_process_user_message_set_app_ll_ts (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2916 of file dlt-daemon.c.
References DltDaemon::applications, DltDaemon::contexts, dlt_daemon_application_find(), DLT_DAEMON_TEXTBUFSIZE, dlt_daemon_user_send_log_level(), DLT_FD_MINIMUM, dlt_log(), DLT_RCV_REMOVE, DLT_RCV_SKIP_HEADER, dlt_receiver_check_and_get(), DltDaemonContext::log_level, NULL, DltDaemon::num_applications, DltDaemonApplication::num_contexts, PRINT_FUNCTION_VERBOSE, DltDaemonContext::trace_status, and DltDaemonContext::user_handle.
int dlt_daemon_process_user_message_unregister_application (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2436 of file dlt-daemon.c.
References DltDaemonApplication::apid, DltDaemonContext::apid, DltDaemon::applications, DltDaemon::contexts, DltDaemonContext::ctid, dlt_daemon_application_del(), dlt_daemon_application_find(), dlt_daemon_context_del(), dlt_daemon_log_internal(), DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DLT_RCV_REMOVE, DLT_RCV_SKIP_HEADER, dlt_receiver_check_and_get(), NULL, DltDaemon::num_applications, DltDaemonApplication::num_contexts, and PRINT_FUNCTION_VERBOSE.
int dlt_daemon_process_user_message_unregister_context (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * rec, int verbose)
Definition at line 2537 of file dlt-daemon.c.
References dlt_daemon_context_del(), dlt_daemon_context_find(), dlt_daemon_control_message_unregister_context(), dlt_daemon_log_internal(), DLT_DAEMON_SEND_TO_ALL, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), DLT_RCV_REMOVE, DLT_RCV_SKIP_HEADER, dlt_receiver_check_and_get(), DltDaemonLocal::flags, NULL, PRINT_FUNCTION_VERBOSE, and DltDaemonFlags::rflag.
int dlt_daemon_process_user_messages (DltDaemon * daemon, DltDaemonLocal * daemon_local, DltReceiver * receiver, int verbose)
Definition at line 1948 of file dlt-daemon.c.
References DltReceiver::buf, DltReceiver::bytesRcvd, dlt_daemon_process_user_message_not_sup(), dlt_log(), dlt_receiver_move_to_begin(), dlt_receiver_receive_fd(), dlt_receiver_remove(), dlt_user_check_userheader(), DLT_USER_MESSAGE_NOT_SUPPORTED, DltDaemonLocal::flags, NULL, PRINT_FUNCTION_VERBOSE, process_user_func, and DltDaemonFlags::vflag.
Referenced by dlt_connection_get_callback().
int dlt_daemon_send_message_overflow (DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 2083 of file dlt-daemon.c.
References dlt_daemon_control_message_buffer_overflow(), DLT_DAEMON_ERROR_OK, DLT_DAEMON_ERROR_UNKNOWN, DLT_DAEMON_SEND_TO_ALL, dlt_log(), DltDaemon::overflow_counter, and PRINT_FUNCTION_VERBOSE.
Referenced by dlt_daemon_log_internal(), and dlt_daemon_process_user_message_log().
int dlt_daemon_send_ringbuffer_to_client (DltDaemon * daemon, DltDaemonLocal * daemon_local, int verbose)
Definition at line 3061 of file dlt-daemon.c.
References DltDaemon::client_ringbuffer, data, dlt_buffer_copy(), dlt_buffer_get_message_count(), dlt_buffer_remove(), dlt_daemon_change_state(), dlt_daemon_client_send(), DLT_DAEMON_ERROR_OK, DLT_DAEMON_ERROR_UNKNOWN, DLT_DAEMON_RCVBUFSIZE, DLT_DAEMON_SEND_FORCE, DLT_DAEMON_STATE_SEND_BUFFER, DLT_DAEMON_STATE_SEND_DIRECT, dlt_log(), dlt_uptime(), PRINT_FUNCTION_VERBOSE, and DltDaemon::state.
Referenced by dlt_daemon_process_client_connect(), and dlt_daemon_process_one_s_timer().
void dlt_daemon_signal_handler (int sig)
Definition at line 1252 of file dlt-daemon.c.
References DLT_DAEMON_LOCK_FILE, DLT_DAEMON_TEXTBUFSIZE, dlt_log(), dltFifoBaseDir, g_exit, and str.
Referenced by dlt_daemon_local_init_p1().
int main (int argc, char * argv[])
Main function of tool.
Definition at line 583 of file dlt-daemon.c.
References create_timer_fd(), dlt_daemon_change_state(), dlt_daemon_free(), dlt_daemon_handle_event(), dlt_daemon_local_cleanup(), dlt_daemon_local_connection_init(), dlt_daemon_local_init_p1(), dlt_daemon_local_init_p2(), dlt_daemon_log_internal(), dlt_daemon_logstorage_setup_internal_storage(), dlt_daemon_prepare_event_handling(), DLT_DAEMON_STATE_BUFFER, DLT_DAEMON_STATE_SEND_DIRECT, DLT_DAEMON_TEXTBUFSIZE, dlt_gateway_init(), DLT_GATEWAY_TIMER_INTERVAL, dlt_get_version(), dlt_log(), dlt_log_init(), dlt_log_set_filename(), dlt_log_set_level(), dlt_mkdir_recursive(), DLT_TIMER_ECU, DLT_TIMER_GATEWAY, DLT_TIMER_PACKET, dltFifoBaseDir, DltDaemonLocal::flags, g_exit, DltDaemonFlags::gatewayMode, DltDaemonFlags::loggingFilename, DltDaemonFlags::loggingLevel, DltDaemonFlags::loggingMode, DltDaemonFlags::offlineLogstorageDirPath, option_file_parser(), option_handling(), DltDaemonLocal::pEvent, PRINT_FUNCTION_VERBOSE, DltDaemonFlags::sendECUSoftwareVersion, DltDaemonFlags::sendTimezone, str, DltDaemonFlags::vflag, and DltDaemonFlags::yvalue.
int option_file_parser (DltDaemonLocal * daemon_local)
Option file parser
Definition at line 209 of file dlt-daemon.c.
References DltDaemonFlags::aflag, DltDaemonFlags::autoResponseGetLogInfoOption, DltDaemonFlags::bvalue, DltDaemonFlags::contextLogLevel, DltDaemonFlags::contextTraceStatus, DltDaemonFlags::ctrlSockPath, DltDaemonFlags::cvalue, DltDaemonLocal::daemonFifoSize, DLT_DAEMON_DEFAULT_CTRL_SOCK_PATH, DLT_DAEMON_FLAG_MAX, dlt_daemon_logstorage_set_logstorage_cache_size(), DLT_DAEMON_RINGBUFFER_MAX_SIZE, DLT_DAEMON_RINGBUFFER_MIN_SIZE, DLT_DAEMON_RINGBUFFER_STEP_SIZE, DLT_GATEWAY_CONFIG_PATH, DLT_LOG_INFO, DLT_LOG_OFF, DLT_LOG_TO_CONSOLE, DLT_LOG_VERBOSE, DLT_SHM_SIZE, DLT_TRACE_STATUS_OFF, DLT_TRACE_STATUS_ON, dltFifoBaseDir, DltDaemonFlags::enforceContextLLAndTS, DltDaemonFlags::evalue, DltDaemonLocal::flags, DltDaemonFlags::gatewayConfigFile, DltDaemonFlags::gatewayMode, DltDaemonFlags::ivalue, DltDaemonFlags::lflag, DltDaemonFlags::loggingFilename, DltDaemonFlags::loggingLevel, DltDaemonFlags::loggingMode, DltDaemonFlags::mflag, DltDaemonFlags::nflag, NULL, DltDaemonFlags::offlineLogstorageCacheSize, DltDaemonFlags::offlineLogstorageDelimiter, DltDaemonFlags::offlineLogstorageDirPath, DltDaemonFlags::offlineLogstorageMaxCounter, DltDaemonFlags::offlineLogstorageMaxCounterIdx, DltDaemonFlags::offlineLogstorageMaxDevices, DltDaemonFlags::offlineLogstorageTimestamp, DltDaemonFlags::offlineTraceDirectory, DltDaemonFlags::offlineTraceFilenameTimestampBased, DltDaemonFlags::offlineTraceFileSize, DltDaemonFlags::offlineTraceMaxSize, DltDaemonFlags::pathToECUSoftwareVersion, DltDaemonFlags::rflag, DltDaemonLocal::RingbufferMaxSize, DltDaemonLocal::RingbufferMinSize, DltDaemonLocal::RingbufferStepSize, DltDaemonFlags::sendECUSoftwareVersion, DltDaemonFlags::sendMessageTime, DltDaemonFlags::sendTimezone, DltDaemonFlags::sflag, DltDaemonFlags::sharedMemorySize, DltDaemonLocal::timeoutOnSend, DltDaemonFlags::vflag, DltDaemonFlags::xflag, and DltDaemonFlags::yvalue.
Referenced by main().
int option_handling (DltDaemonLocal * daemon_local, int argc, char * argv[])
Option handling
Definition at line 120 of file dlt-daemon.c.
References DltDaemonFlags::cvalue, DltDaemonFlags::daemonFifoName, DltDaemonFlags::dflag, DLT_DAEMON_TCP_PORT, dltFifoBaseDir, DltDaemonLocal::flags, DltDaemonFlags::port, usage(), and DltDaemonFlags::userPipesDir.
Referenced by main().
void usage (void)
Print usage information of tool.
Definition at line 94 of file dlt-daemon.c.
References DLT_DAEMON_TEXTBUFSIZE, and dlt_get_version().
Referenced by option_handling().
Variable Documentation
char dlt_timer_conn_types[DLT_TIMER_UNKNOWN+1] static
Initial value:
= {
    [DLT_TIMER_PACKET]  = DLT_CONNECTION_ONE_S_TIMER,
    [DLT_TIMER_ECU]     = DLT_CONNECTION_SIXTY_S_TIMER,
    [DLT_TIMER_GATEWAY] = DLT_CONNECTION_GATEWAY_TIMER,
    [DLT_TIMER_UNKNOWN] = DLT_CONNECTION_TYPE_MAX
}
Definition at line 3122 of file dlt-daemon.c.
Referenced by create_timer_fd().
char dlt_timer_names[DLT_TIMER_UNKNOWN+1][32] static
Initial value:
= {
    [DLT_TIMER_PACKET]  = "Timing packet",
    [DLT_TIMER_ECU]     = "ECU version",
    [DLT_TIMER_GATEWAY] = "Gateway",
    [DLT_TIMER_UNKNOWN] = "Unknown timer"
}
Definition at line 3132 of file dlt-daemon.c.
Referenced by create_timer_fd().
int g_exit = 0
Definition at line 89 of file dlt-daemon.c.
Referenced by dlt_daemon_signal_handler(), and main().
dlt_daemon_process_user_message_func process_user_func[DLT_USER_MESSAGE_NOT_SUPPORTED] static
Initial value:
= {
    dlt_daemon_process_user_message_not_sup,
    dlt_daemon_process_user_message_log,
    dlt_daemon_process_user_message_register_application,
    dlt_daemon_process_user_message_unregister_application,
    dlt_daemon_process_user_message_register_context,
    dlt_daemon_process_user_message_unregister_context,
    dlt_daemon_process_user_message_not_sup,
    dlt_daemon_process_user_message_not_sup,
    dlt_daemon_process_user_message_overflow,
    dlt_daemon_process_user_message_set_app_ll_ts,
    dlt_daemon_process_user_message_not_sup,
    dlt_daemon_process_user_message_not_sup,
    dlt_daemon_process_user_message_not_sup,
    dlt_daemon_process_user_message_marker,
    dlt_daemon_process_user_message_not_sup,
    dlt_daemon_process_user_message_not_sup
}
Definition at line 1925 of file dlt-daemon.c.
Referenced by dlt_daemon_process_user_messages().
char str[DLT_DAEMON_TEXTBUFSIZE] static
Global text output buffer, mainly used for creation of error/warning strings
Definition at line 80 of file dlt-daemon.c.
Referenced by create_timer_fd(), dlt_daemon_close_socket(), dlt_daemon_daemonize(), dlt_daemon_handle_event(), dlt_daemon_init_fifo(), dlt_daemon_init_serial(), dlt_daemon_local_init_p1(), dlt_daemon_process_client_connect(), dlt_daemon_process_control_connect(), dlt_daemon_process_user_message_log(), dlt_daemon_signal_handler(), DLT_DECLARE_CONTEXT(), dlt_logstorage_count_ids(), and main().